### ISSUE TITLE
Link to tutorials on main page dead

### ISSUE THREAD

**Issue by michaelaye** [ioam/holoviews#1122]
On the main page holoviews.org there's a link to tutorials, with the text:
> Now you can download the tutorial notebooks . 

linking to http://assets.holoviews.org/notebooks-1.7dev4.zip
which is dead.

**Comment by jlstevens** [comment]
Thanks for pointing this out!

This is due to the new policy of setting the dev version in ``setup.py`` for pip+archive installs. The version there sets the URL in the docs which is now wrong. This problem was then compounded by the fact that the main website would be copied over from dev portion of the website before the release (violated another assumption we had made).

The best fix right now is to add another step to the dev-release process, uploading the new archive to S3.

**Comment by jbednar** [comment]
Didn't we decide to ship the examples with our packages, and provide a function to install them, like datashader.examples()?  That approach was explicitly designed to prevent this problem, because there is no way to ensure that a static link like that will send people to the version of the examples that matches what they had.

**Comment by jlstevens** [comment]
> Didn't we decide to ship the examples with our packages, and provide a function to install them, like datashader.examples()

That's the plan for 1.7 but while the link still exists, it should work. I'm uploading the new archive now.

**Comment by jlstevens** [comment]
The link is now fixed. Thanks again for reporting this!

Closing.
