### ISSUE TITLE
API to clear and add Stream subscribers

### ISSUE THREAD

**Issue by philippjfr** [ioam/holoviews#1168]
Currently Streams can have subscribers and hidden subscribers. In working on some projects I have found utility in reusing an existing stream but clearing the subscribers manually and manually adding new subscribers since the ``_hidden_subscribers`` are not public API this is quite ugly. It would be nice if Streams offered methods to add new subscribers (``.listen`` or ``.subscribe``?) and clear existing subscribers (``.clear``?).

**Comment by jlstevens** [comment]
It would be reasonable to have an 'advanced user' API for such things that is public but not something most people would need to worry about most of the time. Definitely better than fiddling with underscore attributes!

From what I remember, ``_hidden_subscribers`` partially exists because there needs to be a callback to the plotting class instance. This means calling ``clear`` could break the normal stream examples if it removes all subscribers, including everything in  ``_hidden_subscribers``. This isn't to say ``clear`` is a bad idea, just that it is advanced API for people who really understand how the streams system works in detail.

**Comment by philippjfr** [comment]
Done in PR referenced above.
