### ISSUE TITLE
Item check not working correctly in NdElement

### ISSUE THREAD

**Issue by jlstevens** [ioam/holoviews#119]
I'm currently working on improving ``Table`` which is a subclass of ``NdElement`` and I've noticed various dimension checks are missing: I am able to specify more data dimensions (as a tuple) than declared in the value dimensions and the extra dimensions get dropped.

The things I would expect to happen:

* The number of`` key_dimensions`` should be checked against the length of each key.
* The number of ``value_dimensions`` should be checked against the length of each data tuple.

From a preliminary look at the code, it seems ``_item_check`` isn't called in ``__setitem__`` and is unpacking the data tuples for a reason I can't fathom just yet (which prevents the length check from working). I also want to check if the ``update`` method works correctly with the inherited version of ``_add_item``.

**Comment by philippjfr** [comment]
This will be fixed along with my Element conversion fixes for #140. Both NdElement and Table should simply have been subclassing ``_add_item`` instead of ``__setitem__`` as the baseclass implementation of the latter calls the former, as does the ``update`` method. This ensures that all the key and value dimension checks are applied appropriately at all times.

**Comment by jlstevens** [comment]
Sounds like it is ok to close the issue then.
