### ISSUE TITLE
Easily transpose GridSpace and reverse axes

### ISSUE THREAD

**Issue by basnijholt** [ioam/holoviews#130]
say I have a ```hv.GridSpace```

Is it an idea to give it a property ``.T`` such that it's easily transposed?

Also I would like to reverse the ticks of the axes, but can't figure out how.

**Comment by philippjfr** [comment]
You can shuffle the dimensions of a ``GridSpace`` around like any other ``NdMapping`` type with the ``reindex`` method. Reindex expects a list of dimensions in the order you want them to be. Take the ``GridSpace`` example from the [Containers](http://ioam.github.io/holoviews/Tutorials/Containers#GridSpace):

```python
curve_space = GridSpace(curves,   key_dimensions=['phase', 'frequency'])
```

You can easily transpose the axes with:

```python
curve_space.reindex(['frequency', 'phase'])
```

As for reversing the ticks of the axes, I'm not entirely sure what you mean but if I understand you correctly you'd probably have to declare the values in the order you want them to appear on the Dimension itself, e.g.:

```python
curve_space = GridSpace(curves,   key_dimensions=[Dimension('alphabet', values=['b', 'a', 'c']), 'numbers'])
```

The alphabet Dimension would now be sorted 'b', 'a', 'c' rather than the regular 'a', 'b', 'c'. We could consider adding a ``reverse`` parameter on ``Dimension`` but I'm 100% convinced we should.

**Comment by jlstevens** [comment]
Seems to me that using ``reindex`` is easy enough and works across HoloViews. I'm certainly not convinced that a transpose ``.T`` method is really necessary because of this.

@basnijholt  I'll close this issue for now but we can continue to discuss any new comments or proposals you may have.

**Comment by jbednar** [comment]
It sounds like the above explanation ought to be put into a tutorial, as it's not obvious.

**Comment by jlstevens** [comment]
Agreed. This should be mentioned in one of our open documentation issues or a new documentation issue should be created.

**Comment by rchurt** [comment]
Out of curiosity, did you ever add the `reverse` parameter to `Dimension`? I have a `GridSpace` where I want to flip only the y-axis, but it seems like there should be an easier way than just typing the keys in reverse order into `Dimension`.

<img width="846" alt="Screen Shot 2020-08-20 at 3 34 05 PM" src="https://user-images.githubusercontent.com/14302923/90832428-9b188c00-e2fa-11ea-8fb4-29b1c8403da9.png">

I think that a potentially even more intuitive way would be to add an `origin` option to `GridSpace` that could be used in the following way to achieve the same result:
```
hv.GridSpace(images_dict, kdims=['column', 'row']).opts(origin='top_left')
```

**Comment by m-beau** [comment]
Hi,

Is there any simple way to order a NdLayout top to bottom then left to right instead of the default left to right then top to bottom, for a given .cols(n_cols)? I am asking for an alternative to the transpose parameter. As a feature request, it should be very useful to add a .rows(n_rows) option which would by default sort plots left to right then top to bottom.

Thanks!

**Comment by rchurt** [comment]
@jbednar @jlstevens just wanted to ping you in case you didn't see the previous two comments because this is closed. Thanks!

**Comment by jbednar** [comment]
Those sound like good ideas, but I don't know how to go about implementing them!

**Comment by rchurt** [comment]
Forgot to ping @philippjfr as well.

Regarding adding an `origin` option to `GridSpace`, it seems like there's already a notion of the origin built-in, in a way--it's at the bottom left by default, so if a user passed in `origin=top_left`, you'd just need to reverse the `rows` dimension, as discussed above. Could that work?
