### ISSUE TITLE
Updated Showcase and Introduction notebooks

### ISSUE THREAD

**Issue by jlstevens** [ioam/holoviews#1354]
I think both these notebooks reflect the priorities of early versions of HoloViews i.e matplotlib and especially ``Image`` support and are not suitable anymore.

In particular, I would like Showcase updated very soon after the 1.7 release as it is quite short and we have a lot of far more interesting things to showcase at this point.

The Introduction notebook should also be updated. I would like it to start off as a simplified version of the rich display notebook and work with more than just Images. It should introduce all the various ways of using HoloViews including DynamicMap and streams.

**Comment by philippjfr** [comment]
I strongly agree that both of these notebooks are outdated, ``Showcase`` doesn't really capture many of things that make HoloViews so great and the focus on RGB types in Introduction makes it seem like HoloViews is a library primarily concerned with displaying images. Rather than simply updating them I'd almost say we should start with a blank slate rather than letting the current structure of the notebooks drive our thinking.

**Comment by jlstevens** [comment]
I don't think the idea of a Showcase or an Introduction notebook are outdated. I suppose you mean that we shouldn't try to stick to their current outlines and structure? If so, I agree.

**Comment by philippjfr** [comment]
> I suppose you mean that we shouldn't try to stick to their current outlines and structure? If so, I agree.

Right, we definitely still want these notebooks.

**Comment by jlstevens** [comment]
Not sure this will actually happen for 1.7.1 but it would be good! 

I also think we should all work on updating these notebooks together...

**Comment by jlstevens** [comment]
I think this is addressed as part of the new website where the 'Getting Started' guide is a much better introduction and a showcase at the same time. The two old notebooks still exist in ``doc/Tutorials`` for now.

@philippjfr Close this issue or is there more to discuss?
