### ISSUE TITLE
Collapse and reduce methods are the wrong way round

### ISSUE THREAD

**Issue by jlstevens** [ioam/holoviews#136]
Having been thinking about the API of elements, I have come up with one more suggested improvement. Both ``collapse`` and ``reduce`` are reasonable names but they are the wrong way round!

* Currently ``collapse`` collapses the elements across a HoloMap, leaving the type the same.
* Currently ``reduce`` changes the dimensionality of an element, changing its type.

This seems reasonable until you think about the idiomatic, common semantics normally associated with reduce:

```python
reduce(lambda x,y: x+y, [1,2,3,4])
```

In other words, reduce is for collapsing across elements. You could argue that as our HoloViews elements typically contain numpy arrays, this is already valid and no name swap is required. Although true, I think that in *HoloViews* we tend to think of elements as atomic elements contained in containers such as ``Layouts`` and ``HoloMaps`` instead of thinking of the data inside the elements themselves.

I think the concept of "reducing across a HoloMap`` and "collapsing an Element" would be more idiomatic than the converse. Thoughts?

**Comment by jlstevens** [comment]
This is our last chance to consider this suggestion!

The new Data API is a big improvement and if we *do* want to change these names, this is our chance! It would break backwards compatibility but I think there could be a switch somewhere that could restore the old behavior.

**Comment by jbednar** [comment]
Can they both be called reduce, since they are on different class hierarchies?

**Comment by almarklein** [comment]
I don't have a strong opinion about this. But I would be careful with simply swapping the names; you'd be breaking every occasion where either is used. So if you want to rename, I'd rename to something different, I think.

**Comment by jlstevens** [comment]
Thanks for the suggestions! 

@jbednar Does this mean you agree with the reasoning behind swapping them? Is it worth it and do you think it would be more idiomatic/reduce confusion?

**Comment by jlstevens** [comment]
Instead of swapping them now, if we could just find an alias for ``reduce`` that doesn't have the connotations of idiomatic Python ``reduce``, I think that would do the trick. We could add a deprecation warning on ``reduce`` for this release.

Then this would free us to use ``reduce`` again in a later release e.g if we wanted to replace ``collapse`` with ``reduce`` (we could also just leave collapse alone).

So what would the new name be? I've talked to Philipp and a better name might be ``reduce_dimensions``. I think this would avoids the potential confusion above and is more semantically clear. 

I'm even starting to wonder if both ``collapse`` and ``reduce`` are both really ``reduce_dimensions`` . Different classes and implementations, but same concept each time. This needs a little more thought...

**Comment by jbednar** [comment]
@jlstevens, reduce is something with well defined semantics, while I don't know of any common definition of "collapse" that differs from reduce.  I don't know precisely what reduce() is currently doing (as there is still no Transforming Data tutorial available!!!), but it sounds like a reduction in at least some sense, which is why I'm wondering why not to just call them both reduce.  Right now one would expect both collapse and reduce to be supported by both types of objects, and to do different things, but that's not true.  We need different names for different operations, but if it's fundamentally a reduction of one sort or another, and if it makes no semantic sense to support both of these two things on the same class, then it sounds like only a single name is needed.

**Comment by jbednar** [comment]
As for reduce_dimensions, in terms of a vector, regular Python reduce changes both the type and the dimensionality.  I.e.,  [1,2,3,4] is a four-dimensional vector (represented as a list in this case), and the output of reduce is 10, which is a scalar.  Even if the result were [10] it would still have been reduced to a 1- dimensional vector.  Thus I don't think reduce_dimensions is a useful name, because regular reduce always reduces the dimensions by any interpretation.

**Comment by philippjfr** [comment]
I don't think we'll be switching them around at this point, they're now part of the columns API, the Columnar data tutorial covers them a little bit and we'll have more tutorials to cover what exactly they do. I'm going to close.
