### ISSUE TITLE
Limited conversion flexibility between Elements

### ISSUE THREAD

**Issue by jlstevens** [ioam/holoviews#140]
One of our design goals is to allow flexible conversion between element types, so long as the dimensionality of the data (in terms of key and value dimensions) stays the same. For instance, this *does* work as expected:

```python
c = hv.Curve(range(10), kdims=['weight'], vdims=['height'])
hv.Scatter(c)
```

But unfortunately, the ``Curve`` object ``c`` is not accepted in the constructor of other elements that *also* have a single key and value dimension. In particular, this next example does not work using either ``Bars`` or ``Histogram`` as it should:

```python
hv.Bars(c)
```

We know such conversions are possible via table conversions so I don't see why we can't support such conversions can't be supported in the constructors as well!

**Comment by jlstevens** [comment]
We should think a bit about which element classes should be interchangeable in this way.

* I think charts should be interchangeable if the number of key and value dimensions match, including interchanging with ``Chart3D`` when it makes sense.
* ``Image`` and ``Raster`` should be interchangeable.
* Colorspaces (i.e ``RGB`` and subclasses) should be interchangeable if the number of channels match.
* ``Surface``` and ``Scatter3D`` should be interchangeable and maybe they should be interchangeable with ``Image`` and ``Raster``.

Things that I don't think are interchangeable:

* Annotations can't interchange as their constructors are very varied (unless it is ``HLine`` and ``VLine`` which doesn't make much sense anyway)
* ``Tables`` are very flexible and already have the ``.to`` property for flexible interchange. Might be possible to dump a table with the right number of dimensions into a ``Chart`` and have it work, but I don't think this is strictly necessary.
* You can imagine instances of ``BaseShape`` (a ``Path``) being allowed in the constructor of ``Path`` but I don't think it is that useful. There may be some value of converting a ``Contours`` object to a ``Path``?

That is my summary for what I think should and shouldn't work - I might have missed out something in which case please correct me!

**Comment by philippjfr** [comment]
> I think charts should be interchangeable if the number of key and value dimensions match, including interchanging with Chart3D when it makes sense.

This is already the case, apart from Bars, which isn't a real Chart type (it's an NdElement).

> Image and Raster should be interchangeable.

Also already the case.

> Colorspaces (i.e RGB and subclasses) should be interchangeable if the number of channels match.

Should also already be true.

> Surface and Scatter3D should be interchangeable and maybe they should be interchangeable with Image and Raster`.

Could be made to work but currently only Raster <-> Surface is supported directly.

As far as I can tell the only conversions that are currently not directly supported but should be is between NdElement <-> Chart and maybe Raster <-> Scatter3D. It should be fairly straightforward to make that work though.

**Comment by philippjfr** [comment]
I've now implemented all the constructor conversions (i.e. Element casting) that I think are sensible. It's also resulted in a general cleanup of the constructors so I think this was a good thing to do. Particularly the Table/NdElement constructors were a bit confused and didn't subclass methods as they should have. I've put together a notebook to demonstrate most if not all the possible conversions, which can be viewed [here](http://philippjfr.com/work/share-space/conversion/). I would consider adding this as our first tested non-Tutorial notebook.

**Comment by jlstevens** [comment]
> I would consider adding this as our first tested non-Tutorial notebook.

Sounds reasonable but I would like to have a notebook of *all* the supported conversions of this sort. You have a fair few number already and I don't expect every pairwise conversion but I would like to know about *all* the potential conversion groups (i.e the elements within the same equivalence classes).

That means we get a record of what is possible while we are still on the topic of conversion. We would then have a solid notebook for testing that could later become public reference material as well.

**Comment by philippjfr** [comment]
A number of my recent commits should have sufficiently addressed this issue. I'll extend the Conversion example notebook linked above and add it as a tested notebook but I'll already go ahead and close this issue.

**Comment by jbednar** [comment]
This looks like very useful functionality.  Good job!  Some notes:

1. Personally, I would prefer the notebook to use Layouts to put three or four examples on each line, to make it much easier to scan through a batch of interrelated plots to see how they relate to each other.   E.g. everything in the first section will fit on three lines of three plots each, which will make it simpler to see all the different ways to visualize a set of (x,y) pairs.  It would then seem reasonable to link this in somewhere in the public tutorials, alongside Elements and Containers (or even just as a link from Elements); it would be a very straightforward set of reference data that could be of interest to many people, and requires very little textual explanation because it's quite obvious what it's showing.

2. It would be good to set the appropriate plot option (i.e. reduced numerical precision) to make HeatMap have readable values (and even better to make HeatMap smarter about choosing good precision by default, though that may not be feasible).  

3. I'm not convinced that converting RGB to HSV and back directly is a good thing, at least not as currently implemented.  Right now, it seems to take the first three arrays from one and pass them unmodified to the other, but for actual images, RGB<->HSV has many decades of being well defined to do something completely different, i.e. to convert each RGB triple to the HSV representation of the same color (which is not at all what HoloViews is doing now).  I'm not saying that such array-conversion functionality should be implemented in HoloViews , but that it's confusing to support such conversions at all if it doesn't do the right thing.  If people really do want to pass the arrays unmodified between these two object types, it seems easy enough to do that explicitly by getting handles to the three channels (individually or as a list), and then it will be very clear that such non-color-preserving-conversions were intended).  So I strongly feel that HSV(rgb) should either give an identical-looking plot (but with data internally now stored as HSV), or else be an error.
