### ISSUE TITLE
HoloViewsPlot subclass of Plot

### ISSUE THREAD

**Issue by jlstevens** [ioam/holoviews#145]
I think there should be a class between ``Plot`` which defines a general interface and ``MPLPlot``: this class could contain all the logic that is only about the HoloViews datastructures (e.g computing ranges, applying compositors etc) without also involving a particular plotting library (i.e matplotlib as this time).

I can imagine calling this ``HoloViewsPlot``or similar...

**Comment by philippjfr** [comment]
It goes beyond that unfortunately I've actually started implementing another backend (just to see where our interfaces still need work) and it turns out almost every single plotting class has some code to be shared. The duplication isn't too bad in some cases but ElementPlot, OverlayPlot, CompositePlot and LayoutPlot all have useful methods that should be shared. I may commit my work in progress on a branch at some point so we can discuss together how much of the plotting classes can move to general baseclasses.

**Comment by philippjfr** [comment]
These intermediate plot classes have now been implemented in the form of ``DimensionedPlot`` and various ``Generic*Plot`` baseclasses. It'll take some time to clean them up and document their API properly but it's a first step towards making the plotting code general.

**Comment by jlstevens** [comment]
I think this issue can be closed since the completion of the refactor in #141.

If there is anything else to say, I am happy to reopen this issue.
