### ISSUE TITLE
OptionTree should have a better repr

### ISSUE THREAD

**Issue by philippjfr** [ioam/holoviews#148]
Currently I'm in the process of explaining how the options system works for the SciPy paper submission and want to show a repr for the OptionTree corresponding to show how the set options get stored. However our default repr for the OptionTree does not mention the actual Options that have been set at all. This should be improved.

Currently it looks like this:

```
:OptionTree
   .Curve  :OptionTree
   .Layout :OptionTree
   .Raster :OptionTree
```

My temporary hack for this paper looks like this:

```
:OptionTree 
   .Curve  :OptionTree {'plot': dict(aspect=1.5), 'style': dict(linewidth=1)}
   .Layout :OptionTree {'plot': dict(sublabel_format='{Roman}', aspect_weight=1)}
   .Raster :OptionTree {'style': dict(cmap='Blues')}
```

**Comment by jlstevens** [comment]
Closing this issue as I think it is now being tackled as part of #149

**Comment by jlstevens** [comment]
I've commented on the improved ``OptionTree`` repr in #149 but as that issue is closed, I'll repeat the key points here.

Here is the repr we need to update in the SciPy paper:

```python
OptionTree(groups=['plot', 'style', 'norm'],
   plot={
            'Curve ' : dict(aspect=1.25),
            'Layout' : dict(aspect_weight=1, sublabel_format='{Roman}')},

   style={
            'Curve' : dict(linewidth=3),
            'Image' : dict(cmap='Blues')}
)
```

Which is now accessed as follows (also needs updating):

```python
options = hv.Store.custom_options()[content.id]
```

This time it is a true repr and OptionTree now supports the dictionary option descriptions used elsewhere in HoloViews (i.e in ``__call__`` and ``Renderer.save``).
