### ISSUE TITLE
Sanitation of dimensions for select of a HoloMap not correct yet

### ISSUE THREAD

**Issue by basnijholt** [ioam/holoviews#152]
The select does nothing.
```python
test = lambda x: hv.Curve(np.random.rand(x), kdims=['Superconducting gap'])
hv.HoloMap({1: test(10), 2: test(10)}, kdims=['x']).select(Superconducting_gap=(0.1, 0.2))
```

This also true for ``Path`` and ``Contour``, haven't tried others.

**Comment by philippjfr** [comment]
I've got a commit to fix this outstanding. Will push it tonight.

**Comment by philippjfr** [comment]
Should be fixed by 00b5a665a. Had to fix your example since it doesn't actually match any points in the Curve, using ``.select(Superconducting_gap=(0, 3))`` does it. It does reveal a separate issue though, since the upper bound isn't inclusive but the extents are this happens:

![image](https://cloud.githubusercontent.com/assets/1550771/8190989/da02a250-145d-11e5-81c9-a79138f010e7.png)

**Comment by jlstevens** [comment]
Can this issue be closed? It sounds like it, even if a new issue regarding the bounds needs to be opened.

**Comment by basnijholt** [comment]
The problem I had is solved at least.

**Comment by philippjfr** [comment]
I've opened another issue for the problems with setting extents when slicing Elements. So I'll close this one now.
