### ISSUE TITLE
log scale fails for Bokeh (works for matplotlib)

### ISSUE THREAD

**Issue by wjaskowski** [ioam/holoviews#1679]
```python
%%opts Curve [logy=True]
hv.extension('bokeh')
def sine_curve(phase, freq):
    xvals = [0.1* i for i in range(100)]
    return hv.Curve((xvals, [np.sin(phase+freq*x) for x in xvals]))

phases      = [0, 1, 2]
frequencies = [0.5, 1.0, 1.5]
curves = {(p,f):sine_curve(p,f) for p in phases for f in frequencies}
#del curves[0, 1.0]
hmap = hv.HoloMap(curves, kdims=['phase', 'frequency'])
hmap.layout(dimensions=['phase', 'frequency'])
```
produces a set of empty plots (frames only)

**Comment by philippjfr** [comment]
This is because bokeh breaks when you supply values below zero for the range. It's not clear to me what we can do about this since we'd have to make an arbitrary choice for the y-range lower bound. For now you can us ``hmap.layout(dimensions=['phase', 'frequency']).redim.range(y=(0.01, 1))`` or similar to display just positive values.

**Comment by jlstevens** [comment]
Maybe we should display our arbitrary lower bound as a warning?

**Comment by philippjfr** [comment]
The PR above addressed this, closing.
