### ISSUE TITLE
Clarify that datashader-based examples on holoviews.org require a running Python process

### ISSUE THREAD

**Issue by timothydmorton** [ioam/holoviews#1764]
I'm interested in the examples [here](http://holoviews.org/user_guide/Large_Data.html).  However, there are several side-by-side examples that are supposed to be different but look identical to me.  For example, the "dynamic spreading" example side-by-side plots both look the same, and then also with the final example of the hover tool, they are definitely identical, whereas the one on the left I think is supposed to change the averaging scale with zoom level.

**Comment by jbednar** [comment]
Are you running it locally, or just looking at the website?  These plots all require a running Python process, which is not available on the website, so anything involving dynamic calculations (like the spreading examples) will not function normally.  That's the tradeoff when using datashader -- it makes it possible to work with huge data by never giving the full data to the browser, but since the data's not all in the browser, there needs to be a live Python process to be feeding it the data...

**Comment by timothydmorton** [comment]
Oh ok, I see-- yes, I was just looking at the website.  It's not clear from the documentation on that page that I shouldn't be able to see what is being demo'd by just looking at it in the browser.

**Comment by jbednar** [comment]
The page mentions this issue, but it's deeply buried: "Of course, because the full data is not in the browser, a static export of this page (e.g. on anaconda.org) will only show the initially rendered version, and will not update with new images when zooming as it will when there is a live Python process available."  I wrote that text when that notebook was just a standalone notebook on anaconda.org, but now that it's part of a website where nearly everything works live, we should make that limitation much clearer on this page.  I'll leave this open as a reminder, but if you have any suggestions on how to word it so it would have been clear to you, a PR would be gratefully accepted. :-)

**Comment by timothydmorton** [comment]
Going through the docs some more, the [intro to dynamic maps](http://holoviews.org/user_guide/Live_Data.html) has a nice blue warning box that explains all this in a nicely highlighted way.  Maybe something similar to this should appear on all pages that share this same limitation (in case someone parachutes into one of the pages as I did without carefully reading all the hv documentation)?

**Comment by jbednar** [comment]
Sounds good!  There aren't all that many pages like that; most of the site has statically exportable figures.

**Comment by jlstevens** [comment]
Sounds like a simple clarification would do the trick. Assigning to 1.8.2.

**Comment by philippjfr** [comment]
Added an alert box to the notebook.
