### ISSUE TITLE
using holoviews and bokeh to generate html file without using iPython Notebook

### ISSUE THREAD

**Issue by LuckyGem** [ioam/holoviews#1819]
I have a question about using holoviews and bokeh together to generate html file without using iPython Notebook. I have used bokeh before to generate interactive html file but I am not sure how to do it with holoviews. I want to have a time series graph and a dropdown menu(for example sales of fruit across year, the drop down menu will contain the different kind of frute), the graph will change according to fruite type.
For example, if I want to have a time series graph, with bokeh alone we can 
plot=TimeSeries(data,index='Date',title="fruit X",ylabel='sales')
output_file("graph.html")
show(plot)
I wonder if I can do something similar without using iPython Notebook? Really appreciate you help, thank you.

**Comment by philippjfr** [comment]
Sorry for the delay, we really need to document this better. There are two ways of saving out data:

```
curve = hv.Curve(range(10)) # Could be any HoloViews object

renderer = hv.renderer('bokeh')

# Using renderer save
renderer.save(curve, 'graph.html')

# Convert to bokeh figure then save using bokeh
plot = renderer.get_plot(curve).state

from bokeh.io import output_file, save, show
save(plot, 'graph.html')
# OR
output_file("graph.html")
show(plot)
```

**Comment by Sieboldianus** [comment]
Wow, this should really be added to the Holoviews Userguide [here](http://holoviews.org/user_guide/Deploying_Bokeh_Apps.html)!

**Comment by hygull** [comment]
***Only specify html file name without an extension***
otherwise file will be saved as `graph.html.html`

**Comment by elmbeech** [comment]
@philippjfr - this is semi related.

The explanation was really helpful for me!
I tried to use the same technique to store a hv.Scatter object using **plotly** as backed.
(Because there is a sudden feature on the ploty scatter plot I prefer over the bokeh one.)

This is my attempt and observation: 
```{python}
# load libraries
import pandas as pd
import plotly
import holoviews as hv
hv.extension('plotly')

# generate holoviews scatter object
df = pd.DataFrame([[1,2,3],[4,5,6]]).T
df.columns = ['x', 'y']
obj = hv.Scatter(df, 'x', 'y')
```

First I tried:
```{python}
hv.renderer('plotly').save(obj, 'output')
```
this generates a *output_1.html* file, 
but open it in a webbrowser only shows a **Drawing...** webpage (png attached).

<img width="335" alt="output_1b" src="https://user-images.githubusercontent.com/154283/48169576-9c550200-e2a8-11e8-9965-a0d3cfca8bcc.png">

Then I tried:
```{python}
objstate = hv.renderer('plotly').get_plot(obj).state
plotly.offline.plot(objstate, filename='output_2.html')
```
generates a *output_2.html* file, which worked! (png attached).

<img width="435" alt="output_2b" src="https://user-images.githubusercontent.com/154283/48169637-dde5ad00-e2a8-11e8-9a60-efa8b23b6ff2.png">

I know that the *plotly* backed is beta not fully supported yet.
But It would be super cool if the first method would work too.

I just detected *holoviews* (and *hvplot*) lately. 
I am still quite noob to it and I have no idea where to start hacking in the code base
to get this working.
Maybe you can point me to the right part in the source code?
Or otherwise I let it for the moment as a *"improvement suggestion"*.
Anyhow, till now I am really impressed with what is achievable with *holoviews* and *hvplot*.  

Thank you very much, Elmar

**Comment by zxdawn** [comment]
Is it possible to convert time_series plot to html file:

Here's an example:
No matter how I drug the time bar, the picture is same.

```
import xarray as xr
import hvplot
import geoviews as gv
import cartopy.crs as ccrs
import holoviews as hv

air_ds = xr.tutorial.open_dataset('air_temperature').load()

figure = air_ds.hvplot.quadmesh(
    'lon', 'lat', 'air',projection=ccrs.PlateCarree(),cmap='viridis'
) * gv.feature.coastline * gv.feature.borders

handle = display(figure)

renderer = hv.renderer('bokeh')
renderer.save(figure, 'graph')
```

**Comment by philippjfr** [comment]
Note ``dynamic=False``, also we have a top-level save function now:

```python
import xarray as xr
import hvplot
import hvplot.pandas
import hvplot.xarray
import geoviews as gv
import cartopy.crs as ccrs
import holoviews as hv

air_ds = xr.tutorial.open_dataset('air_temperature').load()

figure = air_ds.hvplot.quadmesh(
    'lon', 'lat', 'air',projection=ccrs.PlateCarree(),cmap='viridis', dynamic=False
) * gv.feature.coastline * gv.feature.borders

hv.save(figure, 'graph.html')
```

**Comment by zxdawn** [comment]
@philippjfr Thanks! It works now 👍

**Comment by LiShi2269** [comment]
> Note `dynamic=False`, also we have a top-level save function now:
> 
> ```python
> import xarray as xr
> import hvplot
> import hvplot.pandas
> import hvplot.xarray
> import geoviews as gv
> import cartopy.crs as ccrs
> import holoviews as hv
> 
> air_ds = xr.tutorial.open_dataset('air_temperature').load()
> 
> figure = air_ds.hvplot.quadmesh(
>     'lon', 'lat', 'air',projection=ccrs.PlateCarree(),cmap='viridis', dynamic=False
> ) * gv.feature.coastline * gv.feature.borders
> 
> hv.save(figure, 'graph.html')
> ```

do you have a top-level show function now?

**Comment by ahuang11** [comment]
There's hvplot.show()

https://github.com/pyviz/hvplot/blob/f041c812a5ab078ad4e8dfbfa952ea8330f5dd0f/hvplot/utilities.py#L47

**Comment by StevenLi-DS** [comment]
I'm having trouble to save a linked plot as an html or some file format that I can simply share with others who don't use jupyter notebook. Here's the example from the doc.

```python
import numpy as np
import holoviews as hv
hv.extension('bokeh')

# Declare some points
points = hv.Points(np.random.randn(1000,2 )).opts(tools=['box_select', 'lasso_select'])

# Declare points as source of selection stream
selection = hv.streams.Selection1D(source=points)

# Write function that uses the selection indices to slice points and compute stats
def selected_info(index):
    arr = points.array()[index]
    if index:
        label = 'Mean x, y: %.3f, %.3f' % tuple(arr.mean(axis=0))
    else:
        label = 'No selection'
    return points.clone(arr, label=label).opts(color='red')

# Combine points and DynamicMap
selected_points = hv.DynamicMap(selected_info, streams=[selection])

layout = points + selected_points
```

Is there any way to save the `layout` together while the interactivity still working? So far, I have only figured out how to [make](https://bokeh.pydata.org/en/latest/docs/user_guide/embed.html) a `bokeh.application`.

**Comment by ahuang11** [comment]
DynamicMaps require a backend server, useful if you want to do computations on the go.

Since you're taking a mean of a selection of points, you can't export it as an HTML because there's additional computations to be made.

If you simply want a linked plot where you can select points and the corresponding points in other subplots get highlighted:

![image](https://user-images.githubusercontent.com/15331990/59979852-233dbd00-95a2-11e9-9774-18b538fcc995.png)


```
import holoviews as hv

hv.extension('bokeh')

df = pd.DataFrame({'x': [0, 1, 2], 'y': [4, 5, 6], 'z': [5, 7, 9]})

linked_plots = (
    (hv.Scatter(df, 'x', 'y') + hv.Scatter(df, 'x', 'z') + hv.Table(df))
    .opts(shared_axes=True)
    .opts('Scatter', tools=['lasso_select'], padding=0.5)
)
hv.save(linked_plots, 'linked_plots.html')
```

**Comment by Muralitharan2789** [comment]
I have did the same as mentioned above, html file is saving and opening while trying from google colab. 

But html saved while running the same code in Pycharm is not opening. Please share any idea or answer for the same. I have struck with this for an day

**Comment by Muralitharan2789** [comment]
Its work with the latest version, If we have to use Python 3.6, bokeh version 2.11 and holoviews latest version worked for my work.

**Comment by Keramatfar** [comment]
> Sorry for the delay, we really need to document this better. There are two ways of saving out data:
> 
> ```
> curve = hv.Curve(range(10)) # Could be any HoloViews object
> 
> renderer = hv.renderer('bokeh')
> 
> # Using renderer save
> renderer.save(curve, 'graph.html')
> 
> # Convert to bokeh figure then save using bokeh
> plot = renderer.get_plot(curve).state
> 
> from bokeh.io import output_file, save, show
> save(plot, 'graph.html')
> # OR
> output_file("graph.html")
> show(plot)
> ```

Thanks, it works but remove styles.
