### ISSUE TITLE
Associativity issue in Layout when labels duplicated

### ISSUE THREAD

**Issue by jlstevens** [ioam/holoviews#188]
This works:

```python
a = hv.Image(np.random.rand(10,10), label='Bar')
print repr((a + a) + a)
```

This doesn't:

```
a = hv.Image(np.random.rand(10,10), label='Bar')
print repr(a + (a + a))
```

And this work again:

```python
a = hv.Image(np.random.rand(10,10), label='Bar')
print repr(a.relabel(label='foo') + (a + a))
```

**Comment by philippjfr** [comment]
This is a serious contender for the most confusing code in HoloViews, but I've finally wrapped my head around it properly. Basically there was no easy way for it to check whether a path was already numbered because the relabeling code assumed paths could be of any length. This generality is not possible unless we track state about which part of the path was autogenerated. So from now on relabeling can only do so for paths of a maximum length of two, corresponding to the group.label naming scheme we have used throughout. The maximum level of nesting you can expect from Layout.relabel_path_items is three, usually of the form {group}.{label}.{roman}.
