### ISSUE TITLE
BoxWhisker and Dataset

### ISSUE THREAD

**Issue by ea42gh** [ioam/holoviews#1937]
given an hv.Dataset
`h=rx_ds.to(hv.BoxWhisker, 'Experiment', 'Error', label='Error')`
is there a way to get a legend attached to each of the BoxWhisker elements?

* if I want to display two copies in a Layout, the original BoxWhisker Plot and a zoomed in version of the plot,
how do I have to specify h.redim.range(???) and what shared_axes, axis_wise options do I have to set to make it work?

I have had no success with either.

* I would welcome additional documentation for hv.Dataset
  The .to() method seems quite inflexible, with the result that the usefulness of
  the hv.Dataset container is not apparent

**Comment by philippjfr** [comment]
>is there a way to get a legend attached to each of the BoxWhisker elements?

You can enable the legend and tie a particular particular dimension to a color using:

```
%%opts BoxWhisker [color_index='Experiment' show_legend=True]
```

>if I want to display two copies in a Layout, the original BoxWhisker Plot and a zoomed in version of the plot,
how do I have to specify h.redim.range(???) and what shared_axes, axis_wise options do I have to set to make it work?

Since merging #2031 ``redim.range`` on BoxWhisker should work correctly, you will also have to set ``+axiswise``. 

Please reopen if you encounter any other issues.
