### ISSUE TITLE
Stream callbacks use experimental JS feature

### ISSUE THREAD

**Issue by philippjfr** [ioam/holoviews#1954]
The JS code for Stream Callbacks uses ``Array.includes`` which apparently is a fairly new addition to the JS world and therefore isn't consistently supported across browsers (see [here](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/includes)). We should switch to an alternative that has better browser support (``indexOf`` probably being the best alternative).

**Comment by jlstevens** [comment]
We have never given much thought to various JS compatibility issues. We tend to use the latest chrome which supports all the nice ES6 features but there are browsers out there with even more miserable Javascript versions.

When we get round to refactoring our JS code, I think we should write everything in ES6 and let a tool like babel handle all the support for older browsers. I recently learned of [this trick](https://philipwalton.com/articles/deploying-es2015-code-in-production-today/) that lets you use the ES6 module system so that modern browsers can load ES6 code without losing support for older browsers that just load transpiled code (without loading things twice). 

This is the approach I would take as it makes supporting older browsers relatively painless while retaining the more pleasant development experience of ES6.
