### ISSUE TITLE
Scale and extents

### ISSUE THREAD

**Issue by vascotenner** [ioam/holoviews#196]
I like to set the extents of a Raster, but keep the aspect ratio of the figure almost square. When I try this, the figure get ridicioulus small:

![screenshot-3](https://cloud.githubusercontent.com/assets/3776190/8456471/efee60fe-200b-11e5-9fe8-0bcfdf380d90.png)

**Comment by basnijholt** [comment]
I think related to https://github.com/ioam/holoviews/issues/167

**Comment by philippjfr** [comment]
For now you will have to manually set the appropriate ``fig_inches`` when plotting single Elements with non-square axes. We should be handling this automatically but currently aren't. The colorbar issue also needs to be fixed but it's a more difficult problem because it's currently specified as a percentage of the main plot and the alternative of setting explicitly in inches is probably even worse.

**Comment by philippjfr** [comment]
This should have been fixed by 20886b36, please test it on your end so I can close the issue.

**Comment by vascotenner** [comment]
This fixes this issue. Thank you very much
