### ISSUE TITLE
Minor API tweaks for the next PyPI release

### ISSUE THREAD

**Issue by jlstevens** [ioam/holoviews#20]
Our core API is now solid (otherwise we wouldn't claim to be version 1.0!) but there are still a few corners of the code where parameter names can be improved and made clearer. We want to fix these names as soon as possible, before too many people (including us!) become reliant on them.

Here is the current list of changes I would personally like to see. 

* ``Plot.show_xaxis -> Plot.xaxis `` : Sounds like a boolean when in fact it is a list of options. Also shorter.
* ``Plot.show_yaxis -> Plot.yaxis `` : Same as above.

Please add any other suggestions you may have or entirely new suggestions below! In addition,  I have submitted a feature request to param that would help make minor API changes easier:  https://github.com/ioam/param/issues/112

**Comment by jlstevens** [comment]
Sounds like something we could easily doe for version `1.0.3`. Thoughts?

**Comment by jlstevens** [comment]
No one has replied so I might go ahead and make these changes before release this week. I am also considering if the figure options e.g ``figure_size`` should be shortened down to simple ``fig_size``.

**Comment by jbednar** [comment]
Yes, the show_ options are very confusing, and should be fixed.

I also vote for changing "sublabel_format" to just "sublabel", so that it is more easily turned off.     

I've no opinion on fig_size, except that if there's a corresponding option in matplotlib with similar semantics, it's good to match the name, and if there's a corresponding option in matplotlib with *different* semantics, it's good *not* to match the name.

**Comment by philippjfr** [comment]
Ideally we'd go through all the plot options one by one and rename them more sensibly. They've mostly just accumulated without working out consistent naming schemes.

**Comment by jlstevens** [comment]
> If there's a corresponding option in matplotlib with different semantics, it's good not to match the name.

I agree it is *good* not to match the name in such circumstances but I don't think it should stop us from using the best name we can think of (whether matplotlib has used it or not).

Matplotlib is only one possible backend and we would do out best to keep the basic plotting class API consistent for new backends. The matplotlib API is generally bad (inherited from Matlab after all!) which means we can pick whatever names we think are most suitable.

**Comment by jbednar** [comment]
Sure. Comparisons with matplotlib are just a tie-breaker -- if there is no overwhelming reason to choose a specific variant of the name (which is common), then what I said is "good" above can help decide.

Yes, going through the plot options one by one is a great idea.  You probably don't have time before Thursday, though.

**Comment by philippjfr** [comment]
As you said we don't have time to go through all of them before this release. I just renamed show_xaxis -> xaxis and show_yaxis -> yaxis, since they were clearly misnamed and were rarely used anyway. We should keep this issue open to continue discussion on sensible naming of plot options.

**Comment by jbednar** [comment]
Ok, good.  I wouldn't say those options are rarely used, though; they are used twice in holoviews/doc/Tutorials/Options.ipynb, and also in imagen/doc/index.ipynb, and imagen/doc/Tutorials/hegde_cc07.ipynb.  So those notebooks will need to be updated, and so will the .zip file of notebooks for HoloViews and for ImaGen.  That's a bit annoying, because it means that the .zip file for ImaGen will require a very specific version of HoloViews.  But it's better to make such fixes now than later...

**Comment by jlstevens** [comment]
This name isn't great either:

```python
xticker = param.ClassSelector(default=None, class_=ticker.Locator, ...)
```

In ``matplotlib.ticker`` you have both tick formatters and tick locators. The name 'xticker' is therefore rather ambiguous and something like 'xticklocator' semantically clearer (although a lot more awkward).

**Comment by jlstevens** [comment]
The ``xticker``, ``yticker`` and `zticker`` options are being removed for 1.3.0. I think we can close this issue as the API changes described here have been implemented. 

In future, we can simply use the "API" tag for any issues regarding the API.
