### ISSUE TITLE
reading DataFrame index as kdim or vdim in DataSet

### ISSUE THREAD

**Issue by spott** [ioam/holoviews#2000]
If you try and pass in the name of an index as a kdim for a DataSet, then the DataSet should accept that and allow you to use an index as a kdim.

**Comment by jbednar** [comment]
If I understand you correctly, that should be working on the github master version of holoviews, as of https://github.com/ioam/holoviews/pull/1946, and will be in the next release.

**Comment by jbednar** [comment]
Oops; didn't read your question closely enough; I thought you were focusing on using the column name rather than a list of column names, which is what the above PR does.  Here, you're saying that we should treat the index as if it were a column.  I really find it mystifying why Pandas treats the index so very differently from other columns, but yes, I agree, we should be able to pass the name of the index just like we can pass the name of regular columns.  We would presumably have to do that as a special case, unfortunately.

Your title suggests using the index as a vdim, not just a kdim, which seems unlikely to be useful because an index is clearly a key rather than a value dimension, but we'd probably have to explicitly disallow usage of the index as a vdim if we support it for kdim, so maybe the title is correct as written.

**Comment by spott** [comment]
>Your title suggests using the index as a vdim, not just a kdim, which seems unlikely to be useful because an index is clearly a key rather than a value dimension, but we'd probably have to explicitly disallow usage of the index as a vdim if we support it for kdim, so maybe the title is correct as written.

I agree... it would be very weird using the index as a vdim, but "weird" and "impossible" are different... and it seems weird to build code to explicitly disallow something just because it is weird.

>We would presumably have to do that as a special case, unfortunately. Meanwhile you can work around it using the Pandas .reset_index() method.

I'm think that this `reset_index()` behavior can probably be done in order to reveal the index if it was asked for.  It creates a shallow dataframe copy, so it shouldn't be user visible, and shouldn't be very expensive.

**Comment by philippjfr** [comment]
Implemented now, see https://github.com/ioam/holoviews/pull/2164.
