### ISSUE TITLE
filled contours and maps

### ISSUE THREAD

**Issue by razvanc87** [ioam/holoviews#212]
Is it possible to use the `Image` element for plotting contours (filled or not)? I just found this amazing piece of software yesterday so I have literally no experience with it, but I didn't see any way of doing this in the tutorials I skimmed through.

Also... is it possible to integrate these plots with `cartopy` or `basemap`? Or both for that matter... `cartopy` preferably cause it uses `matplotlib` axis transformations which makes things easier to deal with.

Thanks!

**Comment by philippjfr** [comment]
Thanks for joining us! For discussions like this it'd be great if you could join us on our [Gitter chat room](https://gitter.im/ioam/holoviews). However to answer your question, I'm guessing you're asking about functionality like ``plt.contourf`` and I'm afraid to say we currently don't have an ``Element`` type for that type of data/visualization but as I already promised another user I will be working on adding this in the coming days.

In terms of ``cartopy`` and ``basemap``, I do have a prototype for a ``basemap`` extension called ``GeoViews``, which I started before I was aware of ``cartopy``. I can push that fairly soon, but as you point out ``cartopy`` is actually nicer for many reasons so it would be great if someone worked on a cartopy HoloViews extension.

**Comment by razvanc87** [comment]
Thanks for the quick response, I actually am not a very big fan (yet... I guess) of this `gitter` thing and didn't cross my mind :). I'll be happy to work on integration with `cartopy` and even the `plt.contourf` stuff, but I need some guidance. If there is any documentation / tutorial on how to add this functionality it would be best. Though I don't really have so much time on my hands these days, probably you'd be 100x faster at implementing these things just because I have no idea how they work in the first place... But if I'm able to help in any way I will.

**Comment by jlstevens** [comment]
Certainly something worth discussing!

Specialized element types (e.g geographic data) is something we want to support and we've been playing around with the idea of a 'holoviews extension'. GeoViews would be an excellent first example of such an extension that could be added to the [extensions repository](https://github.com/ioam/holoviews-extensions) at least while it matures. 

This isn't to say that GeoViews can't be its own project/repository if there is sufficient interest in it and someone to maintain it.

**Comment by philippjfr** [comment]
We're hoping to add some documentation on extending HoloViews very soon, so sorry for the lack of guidance on that part. I'm happy to implement a contourf ``Element`` type myself since as you rightly point out I'll probably be much quicker at it. I'll also try to draw up a simple Tutorial on extending HoloViews over the next few days and will be happy to provide guidance if you give the ``cartopy`` implementation a shot.

**Comment by philippjfr** [comment]
I've added functionality to generate filled contours from ``Raster`` type Elements including Images. Here is a simple example:

```python
%%opts Polygons [colorbar=True] (linewidth=0)
from holoviews.operation import contours
contours(hv.Image(np.random.rand(10, 10)), filled=True, levels=np.linspace(0, 1, 11))
```

The operation outputs an NdOverlay of ``Polygon`` Elements instead of introducing a new ``Element``, so you can access all the contour data. This should eventually migrate to an ``Operations`` Tutorial but for now close this issue. Let us know if you need any help.

**Comment by jbednar** [comment]
Thanks!  Yes, please do put that into a tutorial, and maybe mention that in the Polygons section of the Elements tutorial.

**Comment by razvanc87** [comment]
This is perfect, as soon as I get some time on my hands I'll look at cartopy and how things are wired up internally.
