### ISSUE TITLE
Dask Array Interface

### ISSUE THREAD

**Issue by jakirkham** [ioam/holoviews#2176]
Similarly to how there is an `ArrayInterface` and a `XArrayInterface`, would be nice if there was an interface for using Dask Arrays directly.

**Comment by philippjfr** [comment]
Could you elaborate a little bit on your use case for this? We use the ``ArrayInterface`` to represent tabular datasets with multiple columns (and actually want to eventually recommend against using it because it doesn't allow mixed type columns). The ``XArrayInterface`` on the other hand is used to represent multi-dimensional arrays (or gridded data as we refer to it). If there was a ``DaskArrayInterface`` what kind of data would you use it for? It's not really suitable for representing tabular data for the same reasons as the ``ArrayInterface`` and it's also not suited toward multi-dimensional data because unlike the ``XArrayInterface`` we cannot label the coordinate dimensions.

One thing I can see us doing is adding support for dask arrays on the ``DictInterface`` and ``GridInterface``, which use dictionaries to hold columns and coordinate/value arrays respectively.

**Comment by jakirkham** [comment]
Ah ok, maybe I'm confusing terminology. Sorry. Still learning. :)

I think what I mean is supporting Dask Arrays with the `GridInterface`. Namely am interested in using Dask Arrays to display image stacks.

**Comment by philippjfr** [comment]
Okay that makes complete sense, that's well defined and shouldn't be particularly difficult. Might as well handle it in the ``DictInterface`` case as well while we're at it.

**Comment by jakirkham** [comment]
Great, thanks. What else would be supported if the `DictInterface` were used?

**Comment by philippjfr** [comment]
Basically DictInterface acts as a column store, so it would be a poor man's alternative to a dask DataFrame. Might not be worth it, but I suspect it would be fairly easy to do.

**Comment by jakirkham** [comment]
Thanks for the clarification.

Being ignorant of the details, this is pure speculation. That said, this could be useful in combination with Dask Arrays using structured dtypes.

**Comment by jakirkham** [comment]
Thanks for the clarification.

Being ignorant of the details, this is pure speculation. That said, this could be useful in combination with Dask Arrays using structured dtypes.

**Comment by jlstevens** [comment]
Sounds like an interesting suggestion and there seems no reason this can't be done in principle. That said having a concrete use-case to illustrate how this would be useful would help...

**Comment by jakirkham** [comment]
Our primary use case is imaging processing. We make use of Dask extensively for this and have built a few tools around it. Using holoviews to lazily compute these results as a user inspects them would be very helpful as it would improve interactivity and cutdown on wait time. One piece of doing this will be handling Dask Arrays in holoviews. Though there are other pieces that will mostly happen on the Dask side (e.g. caching, reprioritizing tasks, etc.)

Previously @philippjfr and @jbednar put forward some very nice suggestions to try this with xarray, which works well. Though this adds many more dependencies in our typical workflow to handle file formats that we don't really use. So would like to avoid the extra dependencies and stick to things we already use (i.e. Dask).
