### ISSUE TITLE
Allow better support for diagonal sampling of an Image element

### ISSUE THREAD

**Issue by omrihar** [ioam/holoviews#223]
First of all let me say that I'm really impressed by what you've done and I'm really looking forward to working with it more in the future. I came across a problem, which I guess should be properly stated as a feature request.

As specified in my Stack Overflow question (http://stackoverflow.com/questions/31457922/using-holoviews-sample-function-in-a-diagonal-segment) it is very intuitive to take a slice out of an `Image` element using the `sample` method when it is along one of the axes of the `Image`. It is very unintuitive, however, to do the same for a diagonal line. Ideally, I would like to specify to point `p1` and `p2` and sample the `Image` along the line connecting them. 

The way I do it now, I need to decide to how many points I want to divide the path, then create a list of pairs of points between the two and supply this to `Image`. The result is a `Table` - and getting the list of points out of the table as a `Curve` element only works when the `Table` is one dimensional - i.e. when one of the kdims is constant along the line. Otherwise, using `Table.to.curve` returns one kdim as a function of the other, i.e., a straight line.

**Comment by philippjfr** [comment]
There's two components to this,  and secondly somehow combining two dimensions into one: 

(1) Supporting sampling between two arbitrary points. I'm not 100% sure it should be supported by default, there's all kinds of special types of sampling you might want to do, e.g. linear or log sampling, which is exactly why you can provide raw sampling coordinates. Sampling between two points might be a sufficiently common use case to support by default, what does everyone think?

(2) There should be an easy way to combine two dimensions into one. In your particular case the problem is that if you perform diagonal sampling then both the x- and y-coordinates are changing for each sample, when plotting this as a Curve you have to find some way to somehow reduce 2D coordinates onto a 1D axis. What policy would you expect here? The easiest thing to do would be to allow simply using an index as the x-coordinate, the more complicated but more correct thing to do would be to give the diagonal sample a new scale. I'd need to think more about it, but how would you expect it to behave?

**Comment by omrihar** [comment]
(1) I agree to your analysis. Support sampling between two arbitrary points would be great for me, but I understand if this is not supported by default. 

(2) I think the most generic is using the index as an x-coordinate. Another possibility would be to use dr=sqrt(dx**2 + dy**2) as the increment between two samples, but I'm not sure about how this scale should start. If this is implemented, perhaps use a default index and a keyword argument that can modify this to dr?

**Comment by jbednar** [comment]
If we supported sampling along an arbitrary line, seems like we'd also need to support reducing/collapsing along an arbitrary axis as well, and those will only be valid operations in a very few of the domains in which Image is used.  If we added such support, I'd think we'd only want to do it in a (new) superclass of Image, something that requires x and y to have the same dimensions at least, so that the result is meaningful in any sense.

But really I think this functionality is outside the purview of HoloViews, and instead should be done by some other package.   For instance, you could easily bring the image into Imagen, rotate it in any direction you like, translate it anywhere, then bring it back into HoloViews.  You can then happily slice, reduce, etc. along your new x and y axes.  Imagen uses precisely the same coordinate systems as HoloViews does, so this conversion should be very straightforward, and completely meaningful since Imagen only works with cases where the two spatial dimensions are commensurate.

**Comment by philippjfr** [comment]
I think we've decided this isn't within the scope of HoloViews. I'll close the issue.
