### ISSUE TITLE
Freedom to change round brackets around unit to square brackets

### ISSUE THREAD

**Issue by basnijholt** [ioam/holoviews#227]
I would like to be able to change the round brackets around the units into square brackets.

At the moment the round brackets are hard coded in `holoviews.Dimension.pprint_label`.

```python
@property
def pprint_label(self):
    "The pretty-printed label string for the Dimension"
    unit = '' if self.unit is None else ' (%s)' % self.unit
    return self.name + unit
```

It would be nice to have this parameterized.

**Comment by jbednar** [comment]
It should be easy to add this.  I'd recommend taking a look at the sublabel_format parameter in plotting/plot.py, and making an analogous parameter unit_format for Dimension, defaulting to ' (%s)'.  pprint_label can then do unit = '' if self.unit is None else unit_format % self.unit, and you can then have whatever formatting for the unit that you like.

Probably for generality you'd also want to add a dimension_format parameter, defaulting to ' {dim_name}{unit}'.  If you make a pull request with this, I'd expect it to be approved easily.

**Comment by jlstevens** [comment]
I think we should be wary of adding any new parameters regarding unit formatting to ``Dimension`` because we don't know how we are going to eventually implement proper unit support (e.g supporting unit conversions). Ideally, unit formatting is something that would be handled by whatever units library we end up selecting and is not something that I feel ought to be implemented on ``Dimension`` itself.

Looking to the future, I imagine we will definitely need a way of interfacing whatever units library we end up selecting for HoloViews. We will want to make it easy for the user to customize how the unit system works regardless of the exact details. As a result, I would anticipate some sort of global object/class (i.e a singleton) to control how units are processed and displayed throughout HoloViews that affects the behavior across all ``Dimension`` objects.

Although, I cannot anticipate any other details, we could start with an extremely simple class (called ``Units``, ``UnitSettings`` or ``UnitsSystem``?)  that would simply holds the proposed unit formatter parameter for the time being. This class would then be extended with more parameters and functionality as the unit support eventually becomes more elaborate.

Note this does not necessarily imply that this class is a global unit formatter: even if the individual unit objects format themselves (e.g via ``__repr__``) there will still be global unit options worth customizing. It is also likely that we will want some common utility code for working with units in HoloViews regardless of the exact implementation details. As implementing such a system properly would be a huge task and will require a fair bit of code, I would suggest sticking this new class in a new file (``core/units.py``) to allow a more complete units system to be developed.

**Comment by jbednar** [comment]
I think the support that you outline above is orthogonal to what Bas was asking for and to the solution I proposed.  How a unit formats its own description is indeed something we would want to defer to a separate class, e.g. deciding between "sq. m." or "square meters" or "square metres" or "m^2".  But here we're talking about how the *Dimension* description is formatted, not how the unit itself is formatted.  At the moment, a Dimension is formatted as ``name+" ("+unit+")"``, and I think that such formatting is something only relevant to the Dimension, not to the underlying unit.  I.e., the unit should format itself however it likes (currently just a string, but eventually some more complex object), but however that is, the Dimension should be able to decide whether the unit should be displayed at all, and if so whether with round brackets, square brackets, a comma, or whatever the user wants.  So I don't think we need to add any new classes now; that's about how the unit formats itself, which isn't a problem yet because all units are currently strings.  All we need is support in Dimension for how a Dimension displays the associated unit (if any).

**Comment by jlstevens** [comment]
Alternatively, instead of a new global class, how about a class attribute on ``Dimension``? That seems the right level for this feature and is probably the simplest thing to do for now.

**Comment by philippjfr** [comment]
I do agree that this is about the ``Dimension`` not the unit but I am also wary of adding **two** new parameters. The main problem here is what happens when the unit is None. I think Jean-Luc's suggestion is cleanest for now, if we ever get a request for an axis label formatter (which is likely), we will have to think about this again and find a unified system for all the formatters including axis labels, titles and values. For now though this will address Bas' problem and is a smaller change than adding one or more new parameters.

**Comment by philippjfr** [comment]
I've pushed the change in https://github.com/ioam/holoviews/commit/adce9c0ba067be3f965e23cff377a94cb6fa416b. To change the bracketing you now just set it globally like this:

```python
import holoviews as hv
hv.Dimension.unit_formatter = ' [{unit}]'
```

A separate issue should be opened if we want to add a label_formatter to further customize the axis labels.

**Comment by jbednar** [comment]
Why is unit_formattter a class attribute as opposed to a class Parameter?  I don't see what advantage that would bring, and it means this feature is now undocumented.

**Comment by jbednar** [comment]
Also, shouldn't it be unit_format, not unit_formatter, as it's a string and not an object with methods?  Usually "*verb+*er" is reserved for callable objects or other objects with methods on them.  Plus it doesn't match ``sublabel_format``.

**Comment by jlstevens** [comment]
I agree that ``unit_format`` would be a better name for the reasons you describe...

**Comment by philippjfr** [comment]
Agreed, I just changed it. For now I'd like to keep it as a class attribute because there should probably be a unified way of specifying the formatters, so we are likely to make changes to this in future. A class attribute will be easier to change than a new parameter.

@basnijholt the new way to specify it is:

```python
import holoviews as hv
hv.Dimension.unit_format = ' [{unit}]'
```

**Comment by jbednar** [comment]
How will a class attribute be easier to change than a Parameter?  Seems like by specifying precisely what will be accepted, you will be able to reason more easily about a Parameter than about an arbitrary class attribute, and can thus safely change it.

**Comment by philippjfr** [comment]
I originally argued the same thing with Jean-Luc, might as well make it a parameter, but there is a reason why class attributes will be easier to change later - they're not pickled. That being said I don't have a huge preference either way.

**Comment by jbednar** [comment]
I see.  Well, one could easily argue the opposite -- the fact that a class Parameter's value is pickled means that the behavior for that object will be preserved even if the source code changes later, which allows us to change the behavior without affecting previously pickled data.  :-)  Still, it's a judgement call; as you wish.  I do think it's not generally wise to choose architectures based on a vague notion of what might be needed in the future, compared to a concrete idea of what we're actually using something for right now; the time between now and getting around to something like that in the future can easily be infinite.

**Comment by jlstevens** [comment]
I feel a class attribute is suitable for now. Firstly, I don't think this is something that should be customized per instance (the formatting should be kept consistent otherwise it will get confusing) and secondly I feel the whole way we handle units in general is far from settled.

We can always promote the class attribute to a parameter later if we feel the API is stable enough to be worth documenting. Personally, I strongly suspect will end up finding a better/neater solution soon enough and we will probably want to update the API again once we think about units more carefully.
