### ISSUE TITLE
%load_ext holoviews.ipython produces warning with new IPython 4.0

### ISSUE THREAD

**Issue by basnijholt** [ioam/holoviews#229]
After updating to new jupyter version, the following happens
```%load_ext holoviews.ipython```

now gives:
```
/usr/local/lib/python2.7/dist-packages/IPython/nbformat.py:13: ShimWarning: The `IPython.nbformat` package has been deprecated. You should import from nbformat instead.
  "You should import from nbformat instead.", ShimWarning)
/usr/local/lib/python2.7/dist-packages/IPython/nbconvert.py:13: ShimWarning: The `IPython.nbconvert` package has been deprecated. You should import from ipython_nbconvert instead.
  "You should import from ipython_nbconvert instead.", ShimWarning)
```

**Comment by philippjfr** [comment]
Thanks for trying this out. Haven't had time myself yet, given all the refactoring they've done I'm surprised that's all the warnings we're getting. Will have to look at this over the weekend.

**Comment by stonebig** [comment]
I have a slightly different (updated ?) message, but spirit is the same.
![holoviews_ipython4_warning](https://cloud.githubusercontent.com/assets/4312421/9283804/d4d8343c-42d6-11e5-9b63-076cf9e1ce8f.GIF)

**Comment by philippjfr** [comment]
Thanks for reporting these, we'll have to go through all our IPython imports and if Jupyter is available import the modules from there instead.

**Comment by philippjfr** [comment]
Traced down all these warnings and addressed the issues in HoloViews in commit https://github.com/ioam/holoviews/commit/1fc150fa215a1ffc73f783ea25df217a2420ff07. One of the warnings above is being generated by the nbagg backend in matplotlib, something which has already been fixed in the development version of matplotlib (and they are gearing up for a new release soon). I'd prefer not too clutter up HoloViews with attempts to catch warnings generated by other libraries especially if they've already addressed the issue. Unless someone disagrees I'll close this issue.

**Comment by jlstevens** [comment]
> I'd prefer not too clutter up HoloViews with attempts to catch warnings generated by other libraries especially if they've already addressed the issue.

I would generally agree although I don't want people to think it is HoloViews generating the warning when it is in fact matplotlib especially if it is not *completely* clear to the user that the warning is actually due to matplotlib. This is especially an issue if the user only sees the warning when using nbagg as otherwise the user realize that the warning is not due to HoloViews as soon as matplotlib got used elsewhere.

I would be in favour of eliminating the matplotlib warning (as we know what the warning is and that it isn't important) as long as we can make sure we will remove this extra clutter down the line! And I certainly agree that we don't want such clutter sticking around any longer than absolutely necessary...

**Comment by jbednar** [comment]
I think I'm inclined to agree with JL --- if the warning can be eliminated without anything too horribly nasty, we should silence it.  It feels dirty to add such a workaround for a problem in another library, but that's only a problem for the developers, while the warnings feel dirty for every user every time, which is even worse.

**Comment by philippjfr** [comment]
Okay I agree, but can we also agree to remove this stuff as soon as matplotlib 1.5 is released? Hopefully no one decides to release a distro with Jupyter and matplotlib 1.4.x.

**Comment by jbednar** [comment]
Sure; I think the workaround can be removed as soon as there's no need for it in the latest Anaconda packages, i.e. once matplotlib 1.5 has a conda package in the default channel.  That way there is a simple recipe to silence the warning.

**Comment by philippjfr** [comment]
Okay I've ignored the warnings raised by import the nbagg backend in commit https://github.com/ioam/holoviews/commit/8bd9148f7fa73c99e67403e7be6aebaffa1e241e. This should be all of them, if you find another one please reopen the issue.

**Comment by stonebig** [comment]
thanks... When can we hope for a new release of Holoviews with this change ?
