### ISSUE TITLE
Aspect ratio of images with shared colorbar

### ISSUE THREAD

**Issue by basnijholt** [ioam/holoviews#236]
```python
%%opts Image.B [colorbar=True]
hv.Image(np.random.rand(10,10)) + hv.Image(np.random.rand(10,10), group='B')
```

produces an image with unequal aspect ratios:
![download](https://cloud.githubusercontent.com/assets/6897215/9407809/2037a918-480d-11e5-9571-2f9f14dac5ec.png)

How can I make them the same?

**Comment by philippjfr** [comment]
What's happening here is that both **A** and **B** are assigned the same area. However B is resized slightly because of the colorbar. I'll have to think a little bit about how to fix this. Ideally plots which include colorbars would be assigned a bit more space similar to the way side histograms are handled but getting that just right might be pretty difficult.

**Comment by akhmerov** [comment]
Colorbars are often shared, wouldn't it make sense to include them as separate axes?

**Comment by philippjfr** [comment]
Yes absolutely, that's what we'll have to do.

**Comment by philippjfr** [comment]
I have now implemented colorbars correctly and they should work consistently irrespective of the plot aspects, the number of colorbars etc. Please reopen if there are any further issues.
