### ISSUE TITLE
Problem with string sanitation of $\theta$

### ISSUE THREAD

**Issue by basnijholt** [ioam/holoviews#241]
```python
hv.HoloMap({i: hv.Path((range(3), np.random.rand(3))) for i in range(3)}, key_dimensions=['$\theta$'])
```

gives:

<img width="524" alt="screen shot 2015-08-24 at 14 41 15" src="https://cloud.githubusercontent.com/assets/6897215/9440289/35846cd0-4a6e-11e5-85a5-f11b9eddcbfb.png">

edit: 

I just realised `r'$\theta$'` fixes the problem, but `$\phi$` does work.

**Comment by jlstevens** [comment]
Odd... I assume this is because ``\t`` is the escape code for tabs in Python. I assume there is a similar problem with ``\n`` and the [other escape codes](https://docs.python.org/2.0/ref/strings.html). 

I'm not sure what the best solution is but using the raw string is probably the easiest thing for now...

**Comment by philippjfr** [comment]
As Jean-Luc pointed out this is to do with the various escape codes. When using LaTeX you should either escape the escape codes explicitly or use a raw string as you have done. There's nothing we can really do about this so I'll close the issue.

**Comment by jlstevens** [comment]
>  When using LaTeX you should either escape the escape codes explicitly ...

I'm not sure this is the only solution. For instance, we could automatically replace ``\a`` with ``\\a`` because I doubt we want the system bell in our dimension strings. :-)

You can find the list of [escape codes here](https://docs.python.org/2.0/ref/strings.html) and we would need to decide what should or shouldn't be allowed. For instance, should we really support tabs in dimension names? Maybe it would be better to automatically convert ``\t`` into ``\\t`` because ``\theta`` (and any other LaTeX code beginning with ``\t``) might be the more common and useful case.

**Comment by philippjfr** [comment]
This might be worth considering but I do have one minor objection. Presumably we wouldn't want to escape the newline character ``\n`` , which means our handling would be inconsistent. You could do ``'\theta'`` but would need ``r'\nu``. I don't have a strong opinion on this though.

**Comment by jlstevens** [comment]
>  Presumably we wouldn't want to escape the newline character \n

I'm not convinced that multi-line dimension labels really make sense anyway. Which means I would probably be in favor of escaping everything to be consistent.

**Comment by jbednar** [comment]
What's wrong with requiring users to double-escape LaTeX code used here, i.e. ``$\\theta""?

**Comment by jlstevens** [comment]
> What's wrong with requiring users to double-escape LaTeX code used here, i.e. $\\theta$?

That would work but the idea here is to make it as easy for the user as possible. Raw strings already get around this problem and the reason to avoid this escaping is so people can set labels without thinking too much about it.

**Comment by jbednar** [comment]
Hmm.  I guess just saying that no control characters will be respected is fine.  We could always put in something to make ``\\n`` work as a newline, if having newlines were desirable.
