### ISSUE TITLE
Single-valued boolean HeatMap does not display properly

### ISSUE THREAD

**Issue by abourrier** [ioam/holoviews#2449]
Displaying a single-valued boolean array as a HeatMap yields a blank figure.

```python
import holoviews as hv
import numpy as np
import xarray as xr

hv.extension('bokeh')
data_array = xr.DataArray(np.zeros((10,10), dtype=bool), coords=[range(10), range(10)])
hv.HeatMap(data_array)
```

![bokeh_plot](https://user-images.githubusercontent.com/22977572/37407266-861b55fe-2799-11e8-8a92-5eb41af04270.png)

Tested under bokeh 0.12.14 and holoviews 1.9.4

**Comment by marcbernot** [comment]
I can reproduce this bug with bokeh 0.12.14 and holoviews 1.9.4/1.9.5/1.10.
This bug seems to be gone with bokeh 0.12.15. 

I cannot locate the [change](https://github.com/bokeh/bokeh/blob/0.12.15/CHANGELOG) that made it go away, though. I don't think it is webgl related since hv.Store.renderers['bokeh'].webgl is False by default.

**Comment by philippjfr** [comment]
Thanks @marcbernot that's really helpful, I briefly looked into this and it seemed quite bizarre. Wondering whether this is still worth investigating or whether we should just close and require bokeh 0.12.15.

**Comment by jbednar** [comment]
I'm happy with requiring bokeh 0.12.15.
