### ISSUE TITLE
Small spaced labels are not shown in legend

### ISSUE THREAD

**Issue by vascotenner** [ioam/holoviews#251]
When I have a holomap, where there are small differences in the elements of the kdims, and I create an Overlay, not all the elements are listed in the legend:
```
labels = [1.000,1.001,1.002]
hmap = hv.HoloMap([(label, hv.Curve([(label,label)])) for label in labels], kdims=['Test'])
hmap.overlay('Test')
```
![screenshot](https://cloud.githubusercontent.com/assets/3776190/9498612/f7e5791a-4c1a-11e5-8bc5-cee0d252e4ef.png)

```
labels = [0,0.001,0.002]
hmap = hv.HoloMap([(label, hv.Scatter([(label,label)])) for label in labels], kdims=['Test'])
hmap.overlay('Test')
```
![screenshot-1](https://cloud.githubusercontent.com/assets/3776190/9498618/fccd18a2-4c1a-11e5-9656-4c4139f21935.png)

While this works as expected: it shows all items in the legend.

I understand that it can be uggly to show long numbers, but if any round-off has to be done, better show three legend items. 

Is there a way to customize this?

**Comment by philippjfr** [comment]
I'll be pushing a fix to this very soon. Basically Dimensions have had formatters and type_formatters for a while now but they were awkward to use because you always had to supply the formatter as a function. Now it accepts both string formatter styles. If you want to override the formatting applied to dimension values by type you can simply increase the number of significant figures you want printed:

```python
Dimension.type_formatters[float] = "%.5g"
Dimension.type_formatters[np.float32] = "%.5g"
Dimension.type_formatters[np.float64] = "%.5g"
```

If you want to override the formatter for a specific Dimension you can just do this in your example:

```python
labels = [0,0.001,0.002]
hmap = hv.HoloMap([(label, hv.Scatter([(label,label)])) for label in labels], kdims=[hv.Dimension('Test', formatter='%.8g')])
hmap.overlay('Test')
```

I'll close the issue as soon as I've pushed my changes.
