### ISSUE TITLE
Bring magics completion into IPython itself.

### ISSUE THREAD

**Issue by Carreau** [ioam/holoviews#256]
Do you think the completion on magics could be integrated into IPython itself ?

It is a oft requested feature request, that we would gladly consider integrating into the core.  
If you have thought of a nice way to do that, like a magic methods defined on class-based magics (from a quick glance that how you do it) 
the I think it could be automatically integrated into core IPython at magic registration time. 

(Nice talk at EuroSciPy Btw)

**Comment by jlstevens** [comment]
The tab completion of is implemented using a ``'complete_command'`` hook and is tricky enough that we have  a dedicated class called ``OptsCompleter`` for the ``%opts`` magic (which you can view here [here](https://github.com/ioam/holoviews/blob/master/holoviews/ipython/magics.py#L484-L569)).

This class defines an ``option_completer`` that is aware of all the registered HoloViews elements as well as their applicable style and plot options etc. This allows the tab completion to be dynamic depending on what you've just typed: for instance, after you type ``Image``, only the style/plot options relevant to ``Image`` are shown. Then after you type ``'style('`` or ``plot(`` (or the equivalent short syntax) you only get the appropriate style or plot options respectively.

I would love there to be an easier way to do such conditional tab-completion! Unfortunately, I think it is a tricky problem as the allowable completion is related to the allowable magic syntax which can get quite complicated (we make use of pyparsing). In HoloViews, you could model the conditional tab-completion as a state-machine where the state defines the available options and is conditional on the string before the cursor position. Generalizing this in a sensible way would be quite a challenge!

The most simple and useful thing would probably be an easier way to debug the completer: every time there was a bug, the tab-completion broke and there was no displayed traceback. Perhaps there is already a sensible way to view such exceptions but I had a frustrating time debugging the tab-completion logic due to the lack of immediate feedback.

**Comment by Carreau** [comment]
Ok, I'll try to have a look, and if you have such frustration again, just tell us we will be happy to make things easier.

**Comment by philippjfr** [comment]
It doesn't seem like this is going to be possible because the code is too specialized. Closing.
