### ISSUE TITLE
Canvases does not respond in the downloaded HTML version as they respond inside Jupyter Notebook

### ISSUE THREAD

**Issue by hygull** [ioam/holoviews#2562]
### What I did?
I executed the example given in this http://holoviews.org/reference/containers/bokeh/HoloMap.html#bokeh-gallery-holomap inside Jupyter Notebook.

It worked fine and it responds to user actions (eg. increasing/decreasing frequency) properly.

### Where problem came?
As I wanted to render the Jupyter Notebook's HTML code using Django that's why I downloaded HTML version of Jupyter Notebook but In this HTML the canvas is not responding to user actions.

When I inspect the web page and see the errors, I found some JS related errors as below:

```console
...
...
Uncaught TypeError: Cannot read property 'model' of undefined
    at BokehSelectionWidget.update (Holoviews.html:14213)
    at BokehSelectionWidget.SelectionWidget.set_frame (Holoviews.html:14008)
...
...
```

@philippjfr , can you suggest me any fix for this JS related issue. 

I am trying it, I am not sure whether I will need to download some external JS library.

Thanks.

**Comment by philippjfr** [comment]
Thanks for filing this issue. This is a regression caused by recent changes to MIME type rendering and will urgently need to be fixed. For now I'd suggest downgrading back to 1.9.5 or 1.10.0dev2 or if you're working entirely within the classic notebook you could try setting the environment variable ``HV_DOC_HTML=true``. We will likely have a 1.10.1 release to address this early next week.

@jlstevens @jbednar To be clear HoloMap exports into a notebook html are currently broken.
