### ISSUE TITLE
Plot pd.DataFrame with time index

### ISSUE THREAD

**Issue by bjonen** [ioam/holoviews#257]
While there are a few examples of time series plots in the tutorials, I could not find an example of plotting a `Curve` with a time index. The existing examples I found use  integer columns for month and year to create a time series plot. 

See also this StackOverflow question I opened: http://stackoverflow.com/questions/32318751/holoviews-how-to-plot-dataframe-with-time-index

If this is not available yet, it would be great to add this possibility.

**Comment by philippjfr** [comment]
We have just begun properly integrating pandas (and other) DataFrames with HoloViews, partially because this kind of thing was not possible/too awkward before. It will probably be a few weeks until the ``dataframe`` branch is merged and this is properly supported. 

If you really need it right away you could try to encode your timestamps into matplotlib's date format and then set the appropriate date formatter on the corresponding Dimension, something like I did in the [Exploring Data Tutorial](http://holoviews.org/Tutorials/Exploring_Data). This is a bit of a pain though, so I'd suggest you wait a few weeks until we have proper support.

**Comment by bjonen** [comment]
Great thanks for the info. Let me know when the branch is ready for some testing or if I can be of any help.

**Comment by philippjfr** [comment]
The branch has now been merged, all basic Element types will now support datetime64 arrays. Let me know if you encounter any issues. [See here](philippjfr.com/work/work-in-progress/bokeh-backend/) for an example. Closing.
