### ISSUE TITLE
color cycle not working with string format of hv.opts

### ISSUE THREAD

**Issue by scaine1** [ioam/holoviews#2576]
I dont seem to be able to get color cycles working when supplying the string format to hv.opts
Using the dictionary format works fine.
When using the string format the following warning is given

Warning: Ignoring keyword pair that fails to evaluate: 'color=cycle'

Example code below.

```python
import numpy as np
import holoviews as hv

hv.extension('bokeh')
renderer = hv.renderer('bokeh')

def curve(val):
    xs = range(-10,11)
    ys = [val-x**2 for x in xs]
    return hv.Curve((xs, ys))

curves = hv.Overlay([curve(x) for x in range(0, 100, 10)])

cycle = hv.Cycle('BuGn')
hv.opts("Curve (color=cycle)")
renderer.save(curves, 'string_opts')

hv.opts({'Curve': {'style': dict(color=cycle())}})
renderer.save(curves, 'dict_opts')

```

**Comment by philippjfr** [comment]
Not that in the notebook this does work:

```python
cycle = hv.Cycle()
%opts Curve (color=cycle)
```

So there must be some difference in the scope in which the string format is evaluated in the two cases.

**Comment by philippjfr** [comment]
This is definitely a more general issue, if you look at the gallery example of filled_contours in the GeoViews gallery you'll see the thumbnail is not respecting the specified ``crs`` https://ioam-docs.github.io/geoviews-master/gallery/index.html, presumably because it's not available in whatever scope it's evaluated.
