### ISSUE TITLE
hv.Dataset() doesn't see df.index until df.reset_index()

### ISSUE THREAD

**Issue by ahuang11** [ioam/holoviews#2717]
Not really a bug, but when I do this
```
import pandas as pd
df = pd.DataFrame([1, 2, 3], index=[4, 5, 6], columns=['col1'])
ds = hv.Dataset(df)
```

I get
```
:Dataset   [col1]
```

When I really want
```
:Dataset   [index, col1]
```

Without having to do
```
import pandas as pd
df = pd.DataFrame([1, 2, 3], index=[4, 5, 6], columns=['col1'])
ds = hv.Dataset(df.reset_index())
```

So that I can do this more straightforwardly.
```
ds.to.curve('index', 'col1', [])
```

(I understand hv.Curve(df, 'index', 'col1') works, but if df had more columns, I want the .to.curve() groupby functionality to make into HoloMap)

**Comment by philippjfr** [comment]
We are explicitly not in the business of dropping indexes automatically since we generally aim to simply wrap the users data until they start applying operations to it, however this should absolutely work. My suggestion therefore would be to allow the ``.to`` interface to discover the index and use it if it is present. That should be a fairly straightforward change and although it is providing special treatment for some interfaces, specifically ``PandasInterface`` and the ``DaskInterface``, which we generally try to avoid, I think it is important enough that we should go ahead with it.
