### ISSUE TITLE
pip2/3 install not working

### ISSUE THREAD

**Issue by ahundt** [ioam/holoviews#2776]
I tried to update holoviews with pip2 and pip3 and ran into the following:
```
± pip2 install holoviews --upgrade --user
Collecting holoviews
  Using cached https://files.pythonhosted.org/packages/3b/09/a52d35bd4f59c5d62bf7baf04b2980d697fe4ceecda193c0ce8a4a3f957f/holoviews-1.10.5.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/ahundt/pip-install-CGRjGQ/holoviews/setup.py", line 75, in <module>
        version=get_setup_version("holoviews"),
      File "/tmp/ahundt/pip-install-CGRjGQ/holoviews/setup.py", line 68, in get_setup_version
        return version.Version.setup_version(basepath, reponame, archive_commit="$Format:%h$")
    AttributeError: type object 'Version' has no attribute 'setup_version'
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/ahundt/pip-install-CGRjGQ/holoviews/
-> [1]
± pip3 install holoviews --upgrade --user
Collecting holoviews
  Using cached https://files.pythonhosted.org/packages/3b/09/a52d35bd4f59c5d62bf7baf04b2980d697fe4ceecda193c0ce8a4a3f957f/holoviews-1.10.5.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/ahundt/pip-install-pc44o4v0/holoviews/setup.py", line 75, in <module>
        version=get_setup_version("holoviews"),
      File "/tmp/ahundt/pip-install-pc44o4v0/holoviews/setup.py", line 68, in get_setup_version
        return version.Version.setup_version(basepath, reponame, archive_commit="$Format:%h$")
    AttributeError: type object 'Version' has no attribute 'setup_version'
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/ahundt/pip-install-pc44o4v0/holoviews/

```

**Comment by ceball** [comment]
My guess is that you have an older version of param, which is providing a version.py file incompatible with the current holoviews. If you don't have param 1.6.1, I think that first running `pip2 install --upgrade --user param` or `pip3 install --upgrade param` then upgrading holoviews might solve your problem.

This problem of requiring param at install time for pip users occurs because pip must build holoviews from the sdist before installing it; the problem will go away when holoviews provides wheels on pypi (soon!).

The problem of mismatched param and holoviews versions at build time (e.g. for people using the sdist) will be fixed when holoviews specifies build time dependencies *and* everyone has a new enough version of pip (>=10), i.e. at some point in the future...

**Comment by ahundt** [comment]
Yep that did the trick! Feel free to close this, or if you think this problem could be common enough, you might want to add a check or update line to your packaging script to ensure param is sufficiently up to date for the install, and perhaps update it for the user.

**Comment by jlstevens** [comment]
Glad that worked for you! @ceball What do you think about closing this issue?

**Comment by ahundt** [comment]
Or the easiest thing with no code changes could be to add a line to your install instructions to update pip and param before subsequent steps. :+1:

**Comment by jbednar** [comment]
Sounds to me like (a) this issue should stay open until we provide wheels, and (b) we should provide wheels ASAP, urgently, to avoid this problem for most users.

**Comment by philippjfr** [comment]
Wheels for holoviews and pyviz_comms have now been uploaded.
