### ISSUE TITLE
Discrepancy between image from hv and using Datashader directly

### ISSUE THREAD

**Issue by adamhrosenberg** [ioam/holoviews#2891]
![screen shot 2018-07-24 at 9 09 29 am](https://user-images.githubusercontent.com/14079647/43148052-bb61bcf4-8f21-11e8-806d-6391f0e6fb60.png)

On the left is the saved image from datashader, on the right is the layout / plot from holoviews, datashader, and bokeh. The only difference that I've been able to discern between my two methods is that I'm using the line method to plot with datashader and the curve method with holoviews:
left:
```
    for column in range(1,4):
        agg = cvs.line(df, '0', str(column), ds.count())
        img = tf.shade(agg, how='eq_hist')
        imgs.append(img)

    stacked = tf.stack(*imgs)
    export_image(stacked, data)
```
right:
```
    curvesx = hv.Curve(df.iloc[:, [0,1]])
    curvesy = hv.Curve(df.iloc[:, [0,2]])
    curvesz = hv.Curve(df.iloc[:, [0,3]])
    layout = curvesx * curvesy * curvesz
    renderer = hv.renderer('bokeh').instance(fig='html')
    plot = renderer.get_plot(datashade(layout, dynamic = False)).state
    plot.plot_width = 800
    plot.plot_height = 500
    show(plot)
```

Not only does the data look a little different, (note the bottom of the graph, on the left there is data that is an outlier which doesn't exist on the right). I've tried different aspect ratios, sizes etc. 

In addition, I believe that I'm not generating a large enough image from holoviews, the right side graph seems much lower quality then the saved image, almost as if it is created small and then stretched out.

Any insight?

Thank you.

**Comment by jbednar** [comment]
The HoloViews hv.Curve object uses Datashader's Canvas.line rendering, so that's not an important difference.  But there are other differences in the two approaches above:

- I believe the HoloViews interface is concatenating all curves (separated by NaNs) and aggregating that entire collection of curves, correctly giving you the number of times each curve crosses each pixel, which can then be mapped onto pixel color using eq_hist.
- Your datashader code instead is aggregating each curve separately, doing eq_hist on each such curve, then essentially averaging them all together.  I don't think this is going to give a meaningful plot, or at least not something that has any clear interpretation; I don't know what an average of histogram-equalized images should mean about the underlying distribution.  It's fine to aggregate separately like this, but I'd recommend merging the aggregate arrays, not the images, *then* histogram-equalizing the results.  You should be able to simply sum the separate `agg` arrays, then call `tf.shade()` on the sum.  `tf.stack()` is useful for combining curves with different colors, because aggregation doesn't take color into account, but it's not suitable for operations like aggregations that should be done with the data rather than the pixel colors.
- Whenever you combine multiple separate aggregations like that, you also need to be sure that each of them is being aggregated into the same space, or else it's not meaningful to combine them.  Here it looks like you're using the same Canvas object, and thus the same height and width, but the "outlier" you noticed is perhaps something with a different auto-ranged x and y range, and thus not plotted in the same space as other plots.  You have to ensure that everything you will ever combine all uses the same ranges, to avoid mixing apples and oranges (or sevens and twenties!).

So, you can either put all the data into one big array and then datashade that (for which the time series notebook has a helper function you can use), or else you can aggregate each curve separately *in the same space* (height, width, x_range, and y_range), sum the result, then shade that.  Hope that makes sense.

**Comment by adamhrosenberg** [comment]
Thank you for the response, I'm going to go through this and get back to you

**Comment by adamhrosenberg** [comment]
So I believe the direction you were pointing me in was this code which I've slightly modified from the original tseries notebook. 

```
    aggs = [cvs.line(df, '0', str(c), agg=ds.count()) for c in range(1,4)]
    merged = xr.concat(aggs, 'cols')
    total = merged.sum(dim='cols')
```

From my debugging, aggs is being populated correctly. However, when I try to merge them with the xarray concat method, I get an error
```
    return self.mapping[key]
          KeyError: '1'
```

I've labeled my columns numerically, and have in the past just cast them to a string to reference; however, maybe that isn't the solution here. I've seen in your examples where you have a renamed xarray and use that to merge too, however I've never gotten any of it to really work with my data. Because of this issue was the reason I stacked images to graph multiple curves originally

**Comment by jbednar** [comment]
Maybe you want something like this?

```
import pandas as pd, numpy as np
df = pd.DataFrame([[1, 10, 100], [2, 20, 200]],
                   columns=['0', '1', '2'])
df
```
<img width="117" alt="screen shot 2018-07-24 at 6 12 05 pm" src="https://user-images.githubusercontent.com/1695496/43170907-2d1c346e-8f6d-11e8-9f19-8c3e91809bdf.png">

```
def concat_columns(df, separator=np.NaN):
    x = df.columns[0]
    df = df.append({x:np.nan}, ignore_index=True)
    return pd.concat([df[[x,c]].rename(columns={x:'x', c:'y'}) for c in df.columns[1:]])

df2 = concat_columns(df)
df2
```
<img width="119" alt="screen shot 2018-07-24 at 6 12 31 pm" src="https://user-images.githubusercontent.com/1695496/43170908-32d2c06c-8f6d-11e8-9982-f60649173d39.png">

You should then be able to datashade df2 directly.

**Comment by jbednar** [comment]
(You can of course also concatenate the aggregated arrays, but that's a question for the xarray maintainers, not to do with datashader per se...)

**Comment by adamhrosenberg** [comment]
Ok that makes sense thank you I will give that a try. And for all of the help in general thank you! My last question is related to the quality of the holoviews implementation. I've looked around online trying to find references for increasing the 'size' or resolution of the graph. From what I can tell however, it just seems to be the nature of shading this data. And especially since I'm shading 15 thousand curves etc. With straight lines and scatter plots the graphs seem to look much sharper then curves. Does that seem correct?

**Comment by jbednar** [comment]
Glad to hear it!  I'm not sure what precisely you're getting at in those last comments, but I would imagine it's related to https://github.com/bokeh/datashader/issues/623 .

**Comment by adamhrosenberg** [comment]
I'll look into it thank you
