### ISSUE TITLE
Extremely slow to save a notebook with HoloViews plots

### ISSUE THREAD

**Issue by dclong** [ioam/holoviews#2938]
It's significantly slower to save a notebook with HoloViews plots than a notebook without any HoloViews plot.

**Comment by jbednar** [comment]
Than what?

**Comment by jlstevens** [comment]
This is likely due to the amount of data involved: once the data is published to the notebook, we aren't involved in the process where the notebook is saved. As such, I can only recommend downsampling or reducing the amount of data in the notebook before saving (not sure what else we could do here).

**Comment by philippjfr** [comment]
Agreed, there is almost certainly nothing we can do here.

**Comment by jbednar** [comment]
Just to clarify, it's not that there is nothing that can be done, it's that there isn't much *we* can do at our end.  At the user level there is lots that can be done, because there are many user choices that affect the file size and thus the speed of reading and writing:

- **Matplotlib backend**: HoloViews used with the matplotlib backend currently embeds PNG or SVG images plus a bit of JavaScript.  Important choices:
   * PNG vs SVG: PNG images are fixed in size regardless of dataset size, so to get smaller files use smaller images.  SVG depends on the dataset size; to get smaller files, you can decimate your data or show a smaller range.
   * Number of plots: The number of plots in the notebook directly determines the overall size.  HoloMaps are particularly important here -- each frame of the holomap, whether selected using widgets or in an animation, needs to be stored, and so you can slice out just a few of those if you want to limit your size.
- **Bokeh backend**: Saved files with the Bokeh backend include Bokeh JavaScript code, some HoloViews JS, and then either images or JSON-encoded data for each plot.
    * Inline Bokeh: By default, HoloViews embeds BokehJS into the saved file so that it can be used without an internet connection, but you can set Bokeh's INLINE_RESOURCES to False to pull that code from npm dynamically instead to reduce file size.
    * Raw data vs. Datashader: If you have large datasets, you can use datashade() to turn them into images that will then be embedded into the file instead of the original data, which can greatly reduce the size (though it limits the ability to zoom and select in the output file).
    * Number of plots: Just as for mpl SVG, the total size scales with the number of plots (including HoloMap frames) and the amount of data in them, so you can limit the size by reducing either of those.

In each of these cases, the file size and speed is largely not something that is up to HoloViews; it's about what you choose to embed in the output file.  If you embed big stuff, it gets slow! :-)

Feel free to reopen to provide additional context if there was something that *should* be small and fast but isn't.
