### ISSUE TITLE
using tools=['hover'] with toolbar=None doesn't seem to work

### ISSUE THREAD

**Issue by rabernat** [ioam/holoviews#3006]
I would like to disable the toolbar but still have a hover tool available. I am currently doing this as follows
```python
%%opts Image [tools=['hover'] toolbar=None]
x,y = np.mgrid[-50:51, -50:51] * 0.05
hv.Image(np.sin(x**2+y**3))
```

The hover doesn't work when `toolbar=None`.

**Comment by marcbernot** [comment]
I'm not sure but indeed it looks like when toolbar=None, holoviews disables tools rather than hides the toolbar.
You can use theming in bokeh as explained [in the last section here](http://holoviews.org/user_guide/Plotting_with_Bokeh.html) to get what you want.

```
from bokeh.themes.theme import Theme
theme = Theme(json={'attrs':{'Figure':dict(toolbar_location=None)}})
hv.renderer('bokeh').theme = theme
x,y = np.mgrid[-50:51, -50:51] * 0.05
hv.Image(np.sin(x**2+y**3)).options(tools=['hover'])
```
To cancel the theme you just use no theme : 
`hv.renderer('bokeh').theme = None`

**Comment by philippjfr** [comment]
Thanks for the workaround @marcbernot. I didn't realize you could hide the toolbar without disabling the tools. I certainly prefer that behavior so I'll label this as a bug.

**Comment by philippjfr** [comment]
The suggested behavior is now the default.
