### ISSUE TITLE
Cannot export animations?

### ISSUE THREAD

**Issue by ceball** [ioam/holoviews#303]
I'm using the showcase notebook, and trying to export everything, i.e. I have done `hv.archive.auto()`. I get to this cell:
```python
    items = [(k, hv.Image(sine(grid, *k), vdims=['Amplitude'])) for k in keys]
    circular_wave = hv.HoloMap(items, kdims=dimensions)
    circular_wave
```
and I get this error:
```python
Traceback (most recent call last):
  File "[...]/holoviews/ipython/display_hooks.py", line 163, in wrapped
    notebook_archive.add(element, html=html)
  File "[...]/holoviews/ipython/archive.py", line 187, in add
    info=dict(info, notebook=self.notebook_name))
  File "[...]/holoviews/core/io.py", line 667, in add
    rendered = exporter(obj)
  File "[...]/holoviews/plotting/mpl/renderer.py", line 97, in __call__
    data = self._anim_data(anim, fmt)
  File "[...]/holoviews/plotting/mpl/renderer.py", line 223, in _anim_data
    (writer, _, anim_kwargs, extra_args) = self.ANIMATION_OPTS[fmt]
KeyError: None
```

I think you may already be aware of this issue because someone's already encountered it (https://github.com/ioam/topographica/issues/631) - but I couldn't find a holoviews issue for it already. Sorry if I missed something!

**Comment by jlstevens** [comment]
Now that Philipp's refactor of the output magic is complete and archive has been fixed (well ``NotebookArchive``, it it time to look into this. I was getting a different error at the same cell (unrelated to archive I believe):

**ValueError**
CSS must be supplied as Python dictionary

Anyway, I've tracked down the problem and made two simple (but important!) bug fixes in d6d9ba4 and 2d0d328. Now I am able to use ``hv.archive.auto()`` in the Showcase tutorial without any problem.

You may want to verify it is now working as you would expect. Otherwise, I believe it is working correctly and I'll close the issue) but please do tell us if you find a similar problem again!
