### ISSUE TITLE
typeError: gridplot() got an unexpected keyword argument 'width'

### ISSUE THREAD

**Issue by xavArtley** [ioam/holoviews#3109]
Hi,

I have an error since I have updated bokeh from version 0.13.0 => 1.0.0
```
D:\DISC_Project\python_env\python\lib\site-packages\holoviews\plotting\bokeh\plot.py in initialize_plot(self, plots, ranges)
    868             layout_plot = gridplot(children=plot_grid, width=width,
    869                                    toolbar_location=self.toolbar,
--> 870                                    merge_tools=self.merge_tools, **kwargs)
    871 
    872         title = self._get_title(self.keys[-1])

TypeError: gridplot() got an unexpected keyword argument 'width'
```

![image](https://user-images.githubusercontent.com/18531147/47602454-7ba2c780-d9df-11e8-8163-5a08c15ad524.png)

![image](https://user-images.githubusercontent.com/18531147/47602459-8d846a80-d9df-11e8-9c5e-14537425a24f.png)

**Comment by philippjfr** [comment]
Thanks for reporting this, we will be releasing holoviews 1.10.8 with compatibility for bokeh 1.0 in the coming days.

**Comment by philippjfr** [comment]
1.10.8 and 1.10.9 with compatibility for latest bokeh have been released.

**Comment by philippjfr** [comment]
Have you reloaded your kernel after updating holoviews, the traceback clearly shows that ``width`` is not being passed to gridplot, so that's the only scenario I can imagine.

**Comment by jbhiatt** [comment]
that worked! thank you so much!!! after reloading the kernel i got an error
(something about "embed_js") that eventually led me to realize that i
needed to install pyviz, which took a little maneuvering since my conda
install couldnt find an off-the-shelf build of pyviz, but i eventually
figured it out (used "conda install -c pyviz/label/dev pyviz"). thank you
so much again!
