### ISSUE TITLE
tar.gz file missing on pypi

### ISSUE THREAD

**Issue by arunpersaud** [ioam/holoviews#3118]
Hello

it would be great to have a tar-ball on pypi. This is nice for linux distributions who create their packages directly from source and don't want to use wheel. (Trying to update holoviews for opensuse and ran into the problem that 1.10.9 doesn't have  a tar-ball available).

Thanks

Arun

**Comment by philippjfr** [comment]
@jlstevens

**Comment by jlstevens** [comment]
Unfortunately our PyPI upload went wrong for the last release due to annoyances that aren't worth discussing here. Unfortunately, PyPI doesn't let you re-upload your source files so I cannot fix this for this release.

Our next release won't have this issue and in normal circumstances we do make the tarball  available on PyPI. What I have done instead is make the tarball available here:

[holoviews-1.10.9.tar.gz](https://github.com/ioam/holoviews/files/2563907/holoviews-1.10.9.tar.gz)

I hope that helps you for distribution on opensuse! As PyPI doesn't let me make the tarball available via PyPI I'll close this issue as I cannot fix that for 1.10.9.
