### ISSUE TITLE
.opts: possible issues

### ISSUE THREAD

**Issue by ea42gh** [ioam/holoviews#3303]
May be issues:
```
a = hv.Curve(([1,2], [3,21]))
b = hv.Curve(([1,2], [50, -10]))
( a * b).opts(hv.opts.Curve(toolbar='above'))
```
the toolbar position must be specified for Curve, not for Overlay

**Comment by ea42gh** [comment]
```
def show_a_holomap(sz):
    def ith(i):
        x_vals = np.linspace(0,sz,100)
        h1 = hv.Curve( (x_vals,i+sz*np.random.uniform(-2,2,size=100)), label='C1')
        h2 = hv.Curve( (x_vals,sz+  np.random.uniform(-2,2,size=100)), label='C2')
        return hv.Overlay([h1,h2]).relabel('Sz = %4.1f'%sz)
    return hv.HoloMap({ i: ith(i) for i in range(5)}, kdims=['Plot_Number'])\
             .opts(hv.opts.Curve(axiswise=True, framewise=True), hv.opts.Overlay(legend_position='bottom'))
```
Setting the legend_position causes the plot output to disappear

**Comment by philippjfr** [comment]
Can't reproduce any issue in the first example and the second appears to be a bokeh unsatisfiable constraint error. I can't figure why that is but it's not related to ``opts``.

**Comment by ea42gh** [comment]
The first is not a problem per se, just funny: the toolbar position refers to the plot as a whole, so  I expected it to apply to hv.Overlay rather than hv.Curve

I have had no luck with legend_position with the .opts() syntax.
Setting it via the  %%opts cell magic does work, however.

**Comment by philippjfr** [comment]
>The first is not a problem per se, just funny: the toolbar position refers to the plot as a whole, so I expected it to apply to hv.Overlay rather than hv.Curve

This is true of pretty much every option that controls the plot, e.g. width/height/xaxis/xticks etc. For consistency we allow these options to be set on elements and the overlay inherits them. We used to not allow this but changing the option definition just because you overlaid some other item on top the element was really annoying.

>I have had no luck with legend_position with the .opts() syntax. Setting it via the %%opts cell magic does work, however.

Both .opts and %%opts cause the plot to disappear for me due to an unsatisfiable constraint error in bokeh js.
