### ISSUE TITLE
Change in Point size handling?

### ISSUE THREAD

**Issue by jbednar** [ioam/holoviews#466]
Didn't this previously have fixed-sized dots?

![image](https://cloud.githubusercontent.com/assets/1695496/12876108/6c05c748-cdbf-11e5-9b8f-95649a7aefd0.png)

**Comment by jbednar** [comment]
And I *know* this one did:

![image](https://cloud.githubusercontent.com/assets/1695496/12876121/c56f0a1a-cdbf-11e5-8d38-4fd7b0727cbf.png)

**Comment by philippjfr** [comment]
Yes it's changed because the point scaling behavior has changed. Previously size_index was set to 3 but the scaling_factor was set to 1 and point scaling was only enabled if scaling_factor>=1. The recent changes meant that the scaling_factor is actually a scaling factor and has no effect on whether or not the points get scaled by size. So there is no equivalent option, my choices were either to set size_index to None so it would have to be explicitly activated everywhere or to leave it as is and have some plots (like the ones above) change to use point scaling.

**Comment by jbednar** [comment]
Ok.  Can you fix these examples in the tutorial to make them work like they did before, then clarify here what users need to do to get the old behavior back in their own code?  Then the release notes for 1.4.2 can link back to this issue, saying that the default behavior for point sizing has changed and that user code may need updating.

**Comment by jbednar** [comment]
(Not that I'm saying that the old behavior was better, just that if people have code that relied on it, as here, it's important to be able to make it work the same again.

**Comment by philippjfr** [comment]
Okay I fixed the examples in #472. To disable the size being used simply set ``size_index=None``. Will close this issue and add a reference to it from the CHANGELOG.

**Comment by jbednar** [comment]
Looks good; thanks so much!
