### ISSUE TITLE
Exporting tutorial issues

### ISSUE THREAD

**Issue by jbednar** [ioam/holoviews#468]
I'm trying to figure out how to export files as PNG instead of SVG, and tried as a start:

```
If you do not want the pickle files, you can of course turn them off if you prefer, by changing holoviews.archive.auto() to:

from holoviews import Store
holoviews.archive.auto(exporters=[Store.PlotRenderer.instance(holomap=None)])
```

The notebook complains that ``type object 'Store' has no attribute 'PlotRenderer'``, so the code seems to be out of date.  Plus the text says it's about disabling pickles, yet it seems to be about disabling holomaps from the above.  Plus I still can't figure out how to change the default format for non-holomap objects to PNG, and if I did, how to set the resolution.

**Comment by jlstevens** [comment]
> The notebook complains that type object 'Store' has no attribute 'PlotRenderer', so the code seems to be out of date. 

That is correct, and I'll update this shortly. It should be ``hv.Store.renderers['matplotlib']`` instead of ``PlotRenderer``.

> Plus the text says it's about disabling pickles, yet it seems to be about disabling holomaps from the above.

It disables pickling as pickling is in the exporters list by default and this sets it to just use a ``Renderer``. It should probably be made clearer that you are using this explicit list to override the default list which includes the pickler exporter. The ``holomap=None`` is needed as exporting holomaps isn't supported yet as they are currently rendered as single frames (see issue #449). 

> Plus I still can't figure out how to change the default format for non-holomap objects to PNG, and if I did, how to set the resolution.

Here you can use this in the exporters list instead of the outdated ``PlotRenderer``:

```python
hv.Store.renderers['matplotlib'].instance(size=50, fig='png', dpi=72)
```

Note, I haven't tested this yet! If it doesn't work now, then there is a bug in the current state of the code and not just outdated documentation. Is there anything else I can clarify when I fix this notebook?

**Comment by jlstevens** [comment]
I've opened a PR to fix the outdated instructions (see above).

**Comment by jbednar** [comment]
I opened a additional PR for additional fixes (see above).

**Comment by philippjfr** [comment]
Both PRs have been merged.Can we close this issue?

**Comment by jlstevens** [comment]
I think so. We can always reopen it if necessary.
