### ISSUE TITLE
Setting figure size doesn't work

### ISSUE THREAD

**Issue by basnijholt** [ioam/holoviews#51]
I think (hope) I didn't make a mistake, but the next code produces an error:
```
%%opts Image plot[figure_inches=(7,7)]
data = np.mgrid[:100,:100][0]+2*np.mgrid[:100,:100][1]
hv.Image(data, bounds=(0,0,100,100), 
         key_dimensions=[hv.Dimension('x', range=(-200,200)), 
                         hv.Dimension('y', range=(-200,200))])
```

Error message:
```
Traceback (most recent call last):
  File "/home/bnijholt/python/env_stable/lib/python2.7/site-packages/holoviews/ipython/display_hooks.py", line 197, in wrapped
    **kwargs)
  File "/home/bnijholt/python/env_stable/lib/python2.7/site-packages/holoviews/ipython/display_hooks.py", line 227, in element_display
    **opts(element, get_plot_size(element, size)))()
  File "/home/bnijholt/python/env_stable/lib/python2.7/site-packages/holoviews/plotting/__init__.py", line 70, in opts
    return dict(figure_inches=size, **Store.lookup_options(obj, 'plot').options)
TypeError: type object got multiple values for keyword argument 'figure_inches'
```

**Comment by basnijholt** [comment]
Just found this discussion on the issue: https://groups.google.com/forum/#!topic/holoviews/MAOQGzdwObI

Quick solution for people with the same issue:
```%%output size=400```

or 

```%%opts Image [image_size=400]```

**Comment by jlstevens** [comment]
Your first post with the traceback is indeed a bug that will be fixed in short order. In general, we would recommend against using the figure_inches parameter unless you genuinely care about the actual figure size in inches. If you just want to make a figure bigger or smaller for viewing  the best thing to do (as you point out) is something like:

```python
%%output size=400
```

This cell magic with works for an individual output. If you want  to change the size throughout the notebook, use the equivalent line magic (e.g. ``%output size=400`` ).

In general, we recommend using the ``%output`` line/cell magic instead of trying to control the size via a plot option as in your second suggestion (which can be made to work but is generally more brittle due to the need to specify the applicable element type).

**Comment by philippjfr** [comment]
Fixed in https://github.com/ioam/holoviews/commit/d94222b7b777b1d78e93aad0369790ca267f0ff7. Will close this now.

**Comment by majidam20** [comment]
@philippjfr , Hi, i am plotting stream data, so i would like to change length of xaxis. for example each update at least length be 15 points (i do not mean width and length or range, ticks) i mean length of show in plot.
Thank you.
