### ISSUE TITLE
exporting pdf from notebook

### ISSUE THREAD

**Issue by RafalSkolasinski** [ioam/holoviews#519]
If you currently try to export pdf (holoviews==1.4.3) image to `pdf` with

``` python
%%output filename="test" fig="pdf" dpi=140
# some code in here that normally display image in notebook
```

it export `pdf` correctly but screws up outputs in notebook, even for other cells. 

P.S. Please feel free to modify description or title of the issue

**Comment by philippjfr** [comment]
Thanks for filing the issue, basically embedding a PDF viewer in the notebook is probably not a good idea and should be disabled. I'd suggest retaining PDF as an export format but disable displaying it in the notebook.

**Comment by jlstevens** [comment]
I would hope the need for PDF is somewhat alleviated now that ``nbconvert`` works better with HoloViews. You should be able to export notebooks to PDF using ``nbconvert`` more easily since 
PR #355 was merged.

@RafalSkolasinski Would this be an acceptable solution for you? As Philipp says, PDF support in the notebook itself is tricky and unlikely to ever work properly. For that reason, I would seriously consider deprecating it.

**Comment by philippjfr** [comment]
For the time being I've recommended using the renderer directly:

```
hv.Store.renderers['matplotlib'].save(obj, filename, 'pdf')
```

**Comment by jlstevens** [comment]
@philippjfr Maybe that is the best solution then? Disable pdf in the output magic but leave support at the renderer level? Certainly makes sense to me!

**Comment by jbednar** [comment]
I don't suppose `%%output` could support saving the output in PDF *and* displaying it in some other format in the notebook?  That seems like something people will very often want, i.e. to be able to work nicely within figures in the notebook, but also to save an always-up-to-date PDF copy so that it will be found by LaTeX or other text-preparation programs for writing papers or reports.

**Comment by RafalSkolasinski** [comment]
From my point of view it would be nice to have support of saving to pdf
(through magic), that would work exactly as saving to png, but not break
whole notebook.

**Comment by jlstevens** [comment]
@RafalSkolasinski Agreed! The problem we've never found a decent solution for inlining PDF output in the browser. If you have any suggestions, we'll definitely consider them.

**Comment by RafalSkolasinski** [comment]
Hmmm... Maybe separate magic for exporting to file that wouldn't influence
normal in line output?

**Comment by jlstevens** [comment]
It has been a while since I last tested it but the ``%%output`` magic has a filename argument. I can't remember how it determines the filetype but I imaging it could do it via the extension. That way if you specify ``.pdf`` it would output it as such. Alternatively, have you looked into the notebook archive (documented in the Exporting tutorial)? You could have a renderer exporter for pdfs...

**Comment by jbednar** [comment]
I don't think inlining PDF into the browser is the issue here, just the ability to get a PDF copy while seeing *some* version of the figure in the notebook (whether PNG or SVG).   The notebook archive support should achieve this, but it is a fairly heavy weight way to do so if the cell output magic could do it...
