### ISSUE TITLE
Adapt GridInterfaces to support Histogram and QuadMesh data

### ISSUE THREAD

**Issue by philippjfr** [ioam/holoviews#547]
We have long struggled to find an appropriate format to store Histogram and QuadMesh data, which store the edges of the bins in 2D and 3D. The dense data interface provides an opportunity to adapt these types to use a general interface. The major component of this work will be to generalize the GridColumns proposal to work with bin edges as well as discrete coordinates.

The steps to get this implemented should roughly follow:
- [x] Adapt GridColumns interface to work with bin edges as key dimension values.
- [x] Change Histogram and QuadMesh to use the data interface.
- [x] Change plotting code to use the interface to access the data.

**Comment by philippjfr** [comment]
After some discussion centered around making sure the design makes sense for different data backends, e.g. xarray and iris, we have come to the conclusion that we will also need an API to access the bin edges of key dimensions. The ``dimension_values`` method would always return the bin centers, while the new method would either compute a best guess for the edges (if only bin centers have been supplied) or just return the stored bin edges. GridColumns would still have to support supplying the data in both formats.

**Comment by jlstevens** [comment]
> The dimension_values method would always return the bin centers, while the new method would either compute a best guess for the edges...

This is useful in some cases but I might want this method only at the interface level and not at the element level, simply because we use ``dimension_values`` all the time but haven't needed edges till now. That way we don't need to add yet another method to elements but make the functionality available for when it is needed.

Alternatively, how about offering a utility to do this? The guessing process sounds like something very general that doesn't depend on the details of the element? If there are stored bin edges, that data should just be accessed directly without using such a guessing utility.

> GridColumns would still have to support supplying the data in both formats.

I believe this would be called ``GridInterface`` now. :-)

Couldn't ``GridInterface`` just make use of such a utility to support different formats (center/edge) in the element constructors?

**Comment by philippjfr** [comment]
Definitely not happening as part of 1.7, will postpone until 1.8.

**Comment by philippjfr** [comment]
Finally done! We're so close to converting all elements.
