### ISSUE TITLE
Slicing over (hv.Image * hv.VLine) 

### ISSUE THREAD

**Issue by basnijholt** [ioam/holoviews#57]
``hv.Image`` and ``hv.VLine`` both have x bounds from (0,2).

When I do:
```
d={x: (fractal * hv.VLine(x)) for x in dots}
hv.HoloMap(d, key_dimensions=['B'])[0:1]
```

Only the VLine will go to one, but the Image is still from 0 to 2.

**Comment by philippjfr** [comment]
When you are slicing a HoloMap, you're not slicing the Elements inside it directly. Have a look at the [Exploring Data](http://ioam.github.io/holoviews/Tutorials/Exploring_Data) to learn how slicing works in HoloViews. The basics are that you always slice the key_dimensions of the outermost container first but can also provide deep indexes, which will be applied to the Elements inside the container.

So if you have a HoloMap of overlays the first slice(s) will correspond to the key_dimensions of the HoloMap, any further indexes/slices will be passed to the Elements of the HoloMap. Since Overlay (unlike NdOverlay) doesn't have any key_dimensions of its own it will pass those additional slices to each Element.

Say we take your 1D HoloMap, the first slice will apply to the first (and only) dimension of the HoloMap, namely dimension 'B'. 

```
d={x: (fractal * hv.VLine(x)) for x in dots}
hv.HoloMap(d, key_dimensions=['B'])[0:1]
```

If you want to slice the 'x' Dimension on each Element instead you supply an additional slice:

```
d={x: (fractal * hv.VLine(x)) for x in dots}
hv.HoloMap(d, key_dimensions=['B'])[:, 0:1]
```

alternatively you can use the select method which allows you to select the dimension you want to slice along by name:

```
hv.HoloMap(d, key_dimensions=['B']).select(x=(0, 1))
```

Hope that helps!

**Comment by basnijholt** [comment]
That really helps yes. One thing I can't figure out is how to select a dimension where the dimension name consists of more than one word.

hv.HoloMap(d, key_dimensions=['B']).select(x=(0, 1), 'Other dimension'=(0,2))

**Comment by philippjfr** [comment]
Here's what I do:

```python
hv.HoloMap(d, key_dimensions=['B']).select(**{'x':(0, 1), 'Other dimension':(0,2)})
```

**Comment by basnijholt** [comment]
Great! 

I tried ``.select`` with an ``Overlay`` of an ``Image`` and ``Curve``, but it doesn't work if I do it like that. 

Am I missing something again?

**Comment by philippjfr** [comment]
It's a fairly subtle concept but HoloViews makes the distinction between key_dimensions, i.e. the dimensions you can index by, and value_dimensions, i.e. the actual value that you are measuring. This means you should choose the appropriate Element type for your purpose.

Image obviously has two spatial dimensions, which you can specify via the key_dimensions. Curve on the other hand only has one, since it's purpose is to an represent the relationship between an independent variable, the single key_dimension, vs. a dependent variables the value_dimension. It sounds to me like the you'd be better off using the Path or Contour Element as they have two spatial/key dimensions. Path/Contours Elements accept a list of Nx2 xy-coordinates, however as they are treated as a single Element all paths inside it will have the same style (I'd consider changing this as creating a lot of Paths can be slow, same applies to Polygon).

**Comment by basnijholt** [comment]
That's clear.

Now I've been trying:
```
gaps[0,0] + gaps[0,0][0:1,5:9] + gaps[0, 0].select(**{'B':(0,1), 'Chemical potential':(5,9)})
```
![download 11](https://cloud.githubusercontent.com/assets/6897215/7560480/d9f4e5fe-f7c3-11e4-9fd5-e2d9e102fbac.png)

As you can see, it doesn't select the correct area. Is this the behaviour you would expect?

**Comment by jlstevens** [comment]
I agree that although the axes look correct after slicing, the actual area that is shown in the slice is incorrect. Philipp, do you have any ideas what is going on?

We are hoping to get as many of these issues sorted soon so we can have a bug-fix release shortly.

**Comment by philippjfr** [comment]
This should be fixed along with https://github.com/ioam/holoviews/issues/76 due to changes to select introduced in https://github.com/ioam/holoviews/commit/df839bea540e87016c08876c5bb46c45220ec875. Will close this issue, please reopen it if you find any problems.
