### ISSUE TITLE
Fixing Axes on Dynamic Maps

### ISSUE THREAD

**Issue by chrisvle** [ioam/holoviews#598]
I am trying to figure out a way to fix the axes utilizing %opts for a dynamic map but have not been able to find anything about it.

**Comment by philippjfr** [comment]
Is there anything in particular you want to change? Depending on what type of Elements you're returning in the DynamicMap, you apply the options to those, e.g.:

```python
%%opts Image [xaxis=None yaxis='right']
hv.DynamicMap(lambda x: hv.Image(np.random.rand(10,10)))
```

**Comment by jbednar** [comment]
I think he wants to set the extents/ranges...

**Comment by philippjfr** [comment]
Ah, yes makes sense. The easiest way to do that is to simply slice the Element before you return it:

```
%%opts Image [xaxis=None yaxis='right']
hv.DynamicMap(lambda x: hv.Curve(np.random.rand(10))[:, 0:1.5])
```

Otherwise you have the option of setting it as the ``range`` on the corresponding dimension or setting the ``extents`` on the Element, which is specified as a tuple of the (left, bottom, right, top) points of the axes. Here's an example that sets the x-axis limits via the dimension and the y-axis limits via the extents:

```
%%opts Image [xaxis=None yaxis='right']
xdim = hv.Dimension('x', range=(0,12))
hv.DynamicMap(lambda x: hv.Curve(np.random.rand(10), kdims=[xdim], extents=(None, 0, None, 1.5)))
```

**Comment by chrisvle** [comment]
`xdim` worked perfectly for me, Thank You!
