### ISSUE TITLE
Pyplot usage

### ISSUE THREAD

**Issue by akhmerov** [ioam/holoviews#599]
Pyplot function calls are heavily linked with the pyplot figure management, and flushing the output to the backends. This makes pyplot a mediocre interface to use in library code, because of potentially harmful interactions with the backend (code has side effects that are hard to control).

Additionally, importing pyplot has irreversible effects (as of mpl v1.5) since it prevents the user from changing the backend.

Therefore it would be beneficial to limit pyplot usage, or even completely avoid pyplot (the latter is only possible if holoviews never uses `nbagg`).

**Comment by philippjfr** [comment]
Thanks for filing the issue, there are a few places where we still use the ``pyplot`` interface rather than going with a fully-OO approach. It's not quite clear to me how we can replace them yet but I'll just list our usage of them:

1. We use ``plt.figure`` to create Figure objects, possible should instantiate ``Figure`` class and ``FigureCanvasAgg`` canvas manually.
2. We use plt.subplot to instantiate subaxes, should see if it it can easily be replaced with ``fig.add_axes`` or similar.

We do want to support the nbagg backend but that has its own issues, which we'll have to look at in more detail.

**Comment by akhmerov** [comment]
> We use plt.figure to create Figure objects, possible should instantiate `Figure` class and `FigureCanvasAgg` canvas manually.

I think this should be exactly what you need.

> We use `plt.subplot` to instantiate subaxes, should see if it it can easily be replaced with fig.add_axes or similar.

Looks like `fig.add_subplot` or `fig.subplot` do the same thing.

**Comment by akhmerov** [comment]
I can confirm that the faulty behavior we observed in holoviews v1.4.3 due to pyplot is now gone in v1.6.2. Therefore this issue is seemingly resolved.

PS Too bad we cannot update because of waiting for #805 ;)
