### ISSUE TITLE
ENH: Support for using bokeh through bokeh server

### ISSUE THREAD

**Issue by toddrjen** [ioam/holoviews#694]
Bokeh can run in a server mode.  This allows the plots to be rendered outside the browser, only using the browser to display the resulting image.  This allows for plots much, much larger than is possible using the existing approach.  It would be great if holoviews let users choose whether to use bokeh directly or through bokeh server.

**Comment by philippjfr** [comment]
Agreed, this has been on our radar for a while now. However, the Bokeh team has been thinking about how to integrate bokeh server with the notebook and it's probably best we hold off until they have come up with a clean solution rather than building our own. We also support callbacks via the notebook server itself already so you can do things like downsampling, but unfortunately that's completely undocumented.

**Comment by philippjfr** [comment]
I've made a start on this in #959 and it works pretty well but there's a few kinks to be worked out so this will likely won't land in a release until after 1.7.

**Comment by philippjfr** [comment]
This is now fully supported in HoloViews and https://github.com/ioam/holoviews/pull/1537 will contain a guide explaining how to use it.
