### ISSUE TITLE
LaTeX in name in key_dimensions of HoloMap

### ISSUE THREAD

**Issue by basnijholt** [ioam/holoviews#71]
This works:

```python
hv.HoloMap({i: hv.Image(np.random.rand(25,25)) for i in range(10)}, key_dimensions=['$\phi$'])
```

This doesn't
```python
hv.HoloMap({(i, j): hv.Image(np.random.rand(25,25)) for i in range(5) for j in range(5)}, key_dimensions=['$\phi$', '$\theta$'])
```

```
Javascript error adding output!
SyntaxError: Unexpected token ILLEGAL
See your browser Javascript console for more details.
```

**Comment by philippjfr** [comment]
Two things, I've escaped slashes in widget labels. That probably needs a more robust fix, so I'll leave the issue open for now. Secondly you'll have to use either ``r'$\theta$'`` or ``$\\theta$`` since Python treats ``\t`` as a horizontal tab, which means you have to declare a raw string or escape it with another backslash.

**Comment by philippjfr** [comment]
I will close now as it seems to be working. If any more issues crop up we'll have to come up with a scheme to sanitize the dimension labels passed to the Jinja template.
