### ISSUE TITLE
Add height_index, width_index, alpha_index, and marker_index to Points/Scatter?

### ISSUE THREAD

**Issue by jbednar** [ioam/holoviews#768]
Right now, one can decide how to map a dimension into the color and size of a Points object, using color_index and size_index, but there's no way to do similarly for alpha, and no way to specify the height and width independently.  For a concrete example where this functionality would be useful, see cell 21 of http://nbviewer.jupyter.org/github/jbednar/bokeh-notebooks/blob/master/tutorial/12%20-%20holoviews.ipynb : 

![image](https://cloud.githubusercontent.com/assets/1695496/16663659/91b36bae-4442-11e6-9962-13ed6a3ec6db.png)

![image](https://cloud.githubusercontent.com/assets/1695496/16663674/9c025ff2-4442-11e6-8ee8-563bb5e213ad.png)

Here the plot is collapsing over the sepal_width and sepal_length values, but instead it would be great if that data could be mapped onto the height and width of the dots.

Similarly, one could easily imagine wanting to use the opacity to show a data value, hence alpha_index.

It would also be useful to have a marker_index, where one of the values is mapped onto one of a finite number of different marker shapes (circle, square, diamond, star, etc.).

**Comment by jlstevens** [comment]
Interesting suggestion!

This would be nice functionality to have. The difficulty is succinctly specifying all the possible visual dimensions that can represent different aspects of the data without making the implementation too complicated.

**Comment by jbednar** [comment]
With this functionality, we could see if we could break a world record for the highest ratio of plot dimensionality to code ever! Each dot would have:

1. x
2. y
3. color
4. height
5. width
6. alpha
7. shape
8. orientation (I guess we need an orientation_index as well...)

and then we could use a GridLayout to get two more dimensions by faceting, plus add a couple of sliders, giving a fully usable 12-dimensional plot that could fit into a single line of user code!
:-)

**Comment by jbednar** [comment]
Might also want aspect_ratio_index, allowing user to do either (size_index, aspect_ratio_index) or (width_index, height_index), but not both.

**Comment by philippjfr** [comment]
So I think I've decided that we should just follow what bokeh does here, which is that certain style attributes can be mapped to a particular column name. I'd suggest each plot declares which style options can also be mapped to a column, e.g. bokeh PointPlot would declare these:

* ``color``
* ``alpha``
* ``marker``
* ``orientation``

You'd then do something like this:

```
hv.Points(df)(style=dict(size='GDP', alpha='Unemployment', marker='Country'))
```

And the PointsPlot would attempt to look for those columns on the Points and map them to the visual attribute. Rather than adding a bunch of ``blah_index`` plot options this is more concise, and makes it explicit that mapping a visual attribute to a column takes precedence over regular colors.

**Comment by jbednar** [comment]
Sounds good to me.

**Comment by jlstevens** [comment]
Seems like a reasonable convention although strings can be quite fragile specifications. That said, an index isn't perfect either and I greatly prefer this to having lots of ``X_index`` parameters.

**Comment by jvivian** [comment]
+1 to marker_index — I was using bokeh's marker mapping to make scientific figures color blind friendly without resorting to muted / ugly color schemes and it'd be great to see this in holoviews.

**Comment by jlstevens** [comment]
@philippjfr Still think this belongs to the 2.0 milestone or do you think it could be done for 1.9?

**Comment by philippjfr** [comment]
So I want to extend this suggestion a bit, since on its own it's not really sufficient. In order to usefully map actual values to a visual attribute you will often need to apply various transforms. Adding special handling around how values are mapped to visual attributes is a pain and will clutter the namespace with a bunch of different options, you just have to look at the options to control the ``size_index`` mapping to see the issue, we currently have ``size_index``, ``scaling_method``, ``scaling_factor`` and ``size_fn`` just to control how the values are mapped to a point size. My proposal therefore extends the specification with a number of useful transforms to do this mapping. As a simple example you could imagine something like this:

```
%%opts Points (alpha=normalize('weight'))
```

Normalize would scale the ``'weight'`` values to range from 0-1 so that they specify valid alpha values. A more complex example might be the size:

```python
%%opts Points (size=scale(log('weight'), factor=10))
```

By nesting transforms like this we can declare more complex mappings from data to visual attributes without adding a huge number of options to control the mapping.

**Comment by jbednar** [comment]
Sounds great.

**Comment by jlstevens** [comment]
I like the basic idea here but I do have one major concern:

Would things like ``log`` be in the namespace generally? Or just inserted into the namespace of the options parser for ``%%opts``? What would it be outside of ``%%opts`` e.g for ``hv.opts`` using the dictionary format?

**Comment by philippjfr** [comment]
Yes, was thinking about that, my two most sensible suggestions which are not exclusive:

* Explicitly using these transform objects and encourage importing them using some common alias e.g. ``hvt.scale(hvt.log('weight'), factor=10)``
* Specifying the transform and column as a string, e.g. ``size='scale(log(weight), factor=10)'``

**Comment by jbednar** [comment]
I think I prefer the first option, because that makes it simpler for people to provide their own arbitrary custom functions.

**Comment by philippjfr** [comment]
>because that makes it simpler for people to provide their own arbitrary custom functions.

They have to be objects and subclasses of some general object that allows them to be nested so there's no reason it can't discover all the available possible transforms.

**Comment by jbednar** [comment]
But that's assuming they have to be some common type, right?

**Comment by philippjfr** [comment]
>But that's assuming they have to be some common type, right?

They have to be anyway, I don't know how they'd work anotherwise. How else could you nest them or specify a column?

**Comment by jlstevens** [comment]
Another suggestion might be a single, flexible object:

```python
%%opts Points (size=hv.dim('weight', min=0, max=10) # Default is 'norm'
%%opts Points (size=hv.dim('weight', fn=np.log)*3
```

I don't link the first option because it is both harder to read and longer than I think is necessary.

**Comment by jlstevens** [comment]
I think almost all cases will be covered by:

* 'Normalization' with a default min of zero and a max of one (both of which you can set)
* 'Scaling' which can be supported by multiplication e.g ``*3``
* An optional unary function. Numpy offers these in its namespace, e.g ``np.log``, ``np.exp``.
* If you really want something more, you can supply your own unary function.

A single object such as ``hv.dim`` is acceptable, a whole family of things with a qualified namespace doesn't seem to be a readable solution.

**Comment by philippjfr** [comment]
```
%%opts Points (size=hv.dim('weight', min=0, max=10) # Default is 'norm'
%%opts Points (size=hv.dim('weight', fn=np.log)*3
```

The min, max thing and fn is too weird for me, but something like this might be okay. Will think about it a bit more.

**Comment by philippjfr** [comment]
I like some of the ideas, but I'm not sure about ``hv.dim``. I do think these transforms should allow nesting and ``dim(dim('dimension', ...), ...)`` is a bit weird, I've considered ``trans``, ``transform`` and ``apply``, can't say I've found something I like yet though. I also think you should be explicit so I think ``fn='norm'`` (with a way of registering other functions as strings) is preferable to defaulting to normalization. I do like being able to apply scaling with ``__mul__`` and would even consider allowing all the other mathematical operators.

Since the object would be in the parser namespace, you'd also not need the ``hv.`` part so it'd be something like:

```python
%%opts Points (size=trans('weight', fn=np.log)) alpha=trans('weight', fn='norm')*10)
```

The cool thing about this is that I've long been thinking about how to apply data transforms easily as requested in https://github.com/ioam/holoviews/issues/237 and I think this would work there too, e.g. to subtract the mean of an Image you could do this:

```python
img.apply(trans('z')-img['z'].mean())
```

And a continuous groupby as requested in https://github.com/ioam/holoviews/issues/1018 could be expressed as:

```
dataset.apply(transform('altitude', fn='cut', bins=[0, 10, 20, 50], labels=['low', 'medium', 'high'])).groupby('altitude')
```

and the same cut function could be used to apply discrete colormapping for a continuous value:

```python
Points (color=transform('altitude', fn='cut', labels=['low', 'medium', 'high'])
```

Hope we can find a better name for this because this could be really great and vastly increase the flexibility of our plotting.

**Comment by philippjfr** [comment]
Made a prototype: https://anaconda.org/philippjfr/op_transforms/notebook

**Comment by jlstevens** [comment]
I like the idea but I don't like the readability aspect, especially in the opts magics which need to be short and readable.

**Comment by jlstevens** [comment]
In other words, this might be ok as long as the common case (i.e >90% of the time) can be expressed with very short, readable expressions. I would not want to encourage long expressions when declaring styles.

In addition, these things need to pickle nicely but that should be possible to arrange.

**Comment by philippjfr** [comment]
>In other words, this might be ok as long as the common case (i.e >90% of the time) can be expressed with very short, readable expressions. I would not want to encourage long expressions when declaring styles.

That's precise the point, it's certainly better than this:

```python
%%opts Points [size_index='weight' size_fn=np.log scaling_factor=10 alpha_index='weight' alpha_fn='norm']
```

And 100x more flexible.

**Comment by jlstevens** [comment]
I understand that. 

What I want to make sure is that the common case is handled nicely in a readable way so that complex expressions are only used when absolutely necessary. Having that flexibility is great but we should aim for utter simplicity 90% of the time while enabling the remaining 10% of cases when necessary.

In other words, ``size=op('weight')`` needs to be our absolute best attempt at a sensible default behavior which I think is probably normalization. Then scaling can be done with ``size=3*op('weight')`` and I'm really hoping most cases don't need anything more complicated than that.

**Comment by philippjfr** [comment]
>In other words, size=op('weight') needs to be our absolute best attempt at a sensible default behavior which I think is probably normalization.

I really think that is terrible implicit behavior and I'm not even convinced 'norm' is the most common thing. Also ``op('weight')`` would normalize and ``op('weight', fn=np.log)`` would not? That's super weird to me, I really think the extra 8 character to type ``op('weight', 'norm')`` are a price worth paying.

**Comment by jlstevens** [comment]
> I really think the extra 8 character to type op('weight', 'norm') are a price worth paying.

I don't. I would rather have two objects ``norm`` and ``logop`` which would support ``*`` for linear scaling.

**Comment by philippjfr** [comment]
>I would rather have two objects norm and logop which would support * for linear scaling.

Throwing away all the flexibility this approach affords.

**Comment by jlstevens** [comment]
The advantage of this (as verbose as it is):

```
%%opts Points [size_index='weight' size_fn=np.log scaling_factor=10 alpha_index='weight' alpha_fn='norm']
```

is that (1) the keywords tab-complete and (2) the values are dead simple literals.

Typing ``op('weight', 'norm')`` into ``%%opts`` now involves 1. parens that need to be balanced 2. two pairs of quotes that need to be balanced 3. A comma in between. This is going to be error prone and not something I want to deal with in the simplest case.

I'm all in favour of flexibility as long as the simplest case is *dead* simple and ``op('weight', 'norm')`` does not cut it.

**Comment by philippjfr** [comment]
Surely the simplest case is just this, i.e. no transformation whatsoever:

```
%%opts Points (size='weight')
```

while normalization is really a special case, even if it might be quite common. My main objection with ``op('weight') `` automatically normalizing is what happens if you don't want to normalize, e.g. I just want to scale my value, do I now have to do ``op('weight', None)*10``? 

If you're not totally opposed to multiple objects as your latest suggestion seemed to indicate, I wouldn't object to aliases for ``op`` with the only one I'd supply by default being ``norm`` so that ``op('weight', 'norm')*10`` and ``norm('weight')*10`` being equivalent.

**Comment by jlstevens** [comment]
If by 'multiple', you mean 'two'.

I wouldn't want more than ``op`` and ``norm`` in the parser namespace. I'm not yet sure whether I want it to be ``hv.op`` and ``hv.norm`` and having ``norm`` as an alias for some version of ``op`` is fine.

Here is what I imagine:

1. ``size='weight'``: the size values are directly supplied by the 'weight'.
2. ``size=norm('weight')*1 : unit normalization but you can pick any scale factor.
3. ``size=op('weight')*1`` : Same as option 1 but you can pick any scale factor.
4. ``size=op('weight', ...)`` : Fancier uses of ``op``, e.g for log scaling.

I think that covers most simple cases the way I want without losing flexibility if necessary. Do you agree?

**Comment by philippjfr** [comment]
Yes, I'd be very happy with that and don't see any need for any more than that either. Users can do what they like of course by subclassing ``op`` in whatever way they want, but we won't ship any more than those two.

**Comment by jbednar** [comment]
I'm eager to have the power to do transformations like this.  Plus, the current size_... options are all so obscure and mysterious that it will be a pleasure to deprecate them.  (I have yet to truly understand how they are supposed to work; I always have to just try them!) 

But I keep wondering if there is a syntax that would let us simply pass an arbitrary Python function, evaluated using `literal_eval`, even if we supply a few ourselves that are particularly convenient. I can't concentrate enough today to be sure there is no gotcha here, but would something like this work?

1. ``size='weight'``: the size values are directly supplied by the 'weight'.
2. ``size='weight',norm*5`` : unit normalization with an optional post-scaling factor.
3. ``size='weight',op*5 ``: Same as option 1 but with any chosen post scaling factor.
4. ``size='weight',(lambda x: x ...)``: Any arbitrary function column->column, e.g for log scaling.

Here if a tuple is supplied, the first item is still the column name, and the second is some output_fn (a callable of one argument, which will be given the column as an argument (not the column name, the actual column)).  To use variants 2 and 3 we'd still need to make a superclass ``op`` and a specific subclass ``norm`` that support the usual operators, but there would be no particular reason people *have* to use them; users can just supply any callable they like. 

I could easily be missing some reason this won't work, though.

**Comment by jlstevens** [comment]
> I could easily be missing some reason this won't work, though!

The biggest issue with any new syntax is it will make things harder for the magic parser which already needs to deal with the ``%%opts`` syntax. I think the last suggestion Philipp and I came up with will be ok but I would be wary of anything more unusual/complicated.

**Comment by philippjfr** [comment]
Personally I prefer our proposal over the tuple approach and also think (or maybe hope) it'll be easier on the parser.

**Comment by jbednar** [comment]
So, no comments on the seemingly large difference that the tuple approach allows custom functions like np.log10 to be used directly?

**Comment by jlstevens** [comment]
I don't see why you couldn't pass such functions to ``op`` without using a tuple when necessary.

**Comment by jbednar** [comment]
As an argument?  Seems very clunky.

**Comment by jlstevens** [comment]
Honestly, I think the tuple approach is clunkier. The only alternative is a string syntax that comes along with the dimension dimension e.g ``'weight:norm'``, ``'weight: np.log'``, ``'weight: x**2'`` but that comes with its own set of challenges.

**Comment by philippjfr** [comment]
I don't see an particular issue accepting ``alpha=('weight', np.log)`` as a shorthand for ``alpha=op('weight', np.log)`` but would generally recommend using ``op`` because it can be chained and allows using the mathematical operators.

**Comment by jlstevens** [comment]
If this tuple replaced the need for ``op`` completely, it would be nice to get rid of the need for it in the namespace and save two letters. That isn't the case though, as we want to be able to multiple with scalars and still need something that does normalization. In the end I would prefer to cut out an additional way of doing things if all it does is save two characters in the opts magics.

**Comment by philippjfr** [comment]
I have no strong opinions, I can see the appeal but since it's not fully general I'm also hesitant. It's worth pointing out that at least when using ``.opts`` it saves typing out ``hv.op``.

**Comment by jlstevens** [comment]
> at least when using ``.opts`` it saves typing out ``hv.op``

Using the dictionary format, yes - if you use the string format, it would be in the parser namespace. That said, this still bothers me and we have a tension between a simple literal which doesn't have this problem and getting the flexibility we want.

**Comment by philippjfr** [comment]
Dictionaries make no sense to me in this case, since you could only ever have one key.

**Comment by jlstevens** [comment]
I meant dictionary format in the sense of ``hv.opts(image, {'style':{'alpha':hv.op('weight')})``.

**Comment by philippjfr** [comment]
Ah got you, I thought you were referencing your proposal from above ``'weight:norm', 'weight: np.log', 'weight: x**2'``.

**Comment by jlstevens** [comment]
I see why you thought that string format it was dictionary-like due to the use of the colon. I hadn't noticed that! :-)

**Comment by jlstevens** [comment]
That makes me think, why not consider an actual dictionary e.g ``alpha={'weight':np.log}``? 

It keeps the name as a name without special syntax and I think it is less troublesome for the parser than tuples (no commas, there is only one item). Maybe you could do ``alpha={'weight':3}`` to mean 'weight times 3'?

Just brainstorming this as another way to avoid needing new things in the namespace.

**Comment by philippjfr** [comment]
>Maybe alpha={'weight':[0,1]} or alpha=('weight', [0,1]) means 'normalize into unit range'?

I think that's exceptionally confusing and unclear, and it's definitely not a sufficient declaration since you also want to be able to set the input range for instance. I vote for sticking with ``op``, all other approaches are limited in some way, because tuples make it difficult to pass ``kwargs`` to your function and don't allow the mathematical operator magic. If Jim insists I'd still be okay allowing tuples for the simplest cases but would be happier with one consistent specification.

**Comment by jlstevens** [comment]
> ... all other approaches are limited in some way

I agree. I'm just brainstorming for other ideas.

Maybe everything in the parser namespace should be put onto the ``hv.opts`` object itself. So you could use ``hv.opts.Cycle`` and ``hv.opts.op``. That would qualify these objects in some way, clean things up and would always be immediately accessible when using ``hv.opts`` itself.

If you agree this makes sense, then I think we can go ahead defining the ``op`` and ``norm`` object and ignore the other suggestions.

**Comment by jbednar** [comment]
>  If Jim insists I'd still be okay allowing tuples

I'm definitely not insisting; you guys are implementing this, and so you get to make the final call (unless you need me for a tiebreaker).  I'm not wedded to the tuple format, but I'm still not quite getting some of your objections to it:

> I don't see an particular issue accepting alpha=('weight', np.log) as a shorthand for alpha=op('weight', np.log) but would generally recommend using op because it can be chained and allows using the mathematical operators.

I don't see what you mean; the tuple proposal chains easily (just like any list of output_fns already does). And the tuple form doesn't support mathematical operators any more or less than the non-tuple form; both of them require some special object to be created, and then it works the same for both.

> If this tuple replaced the need for op completely, it would be nice to get rid of the need for it in the namespace and save two letters. That isn't the case though, as we want to be able to multiply with scalars and still need something that does normalization. 

I suppose one could add logic where "weight",5 would mean multiply by 5, but in general I think people will need to multiply *and* add in many cases.  E.g. anything mapping to height needs some minimum height value or else the width won't be visible, which is probably an additive term (or maybe min/max).

I didn't propose the tuple syntax as a way to save two letters, but as something that is conceptually very straightforward to the user: any python callable applied after the column name is used to transform the column before using it for that attribute of the plot.  As a user, I can then see that *anything* can be supplied there, and so I can ignore the special "op" and "norm" things if I just want to do my own thing.  With the other proposals I have to understand those objects before I can do anything, which annoys me.

BTW, if we are following bokeh here, ``size=5`` is a scalar, and ``size='weight'`` uses the column, right?  Presumably then we can supply a function that reduces, right?  E.g. size=``'weight',avg`` (or whatever op syntax you like) to set the size to the average of the given column?

> Maybe alpha={'weight':[0,1]} or alpha=('weight', [0,1]) means 'normalize into unit range'? If you can set the limits like this, you don't need the scalar multiplication.

I would expect that syntax to be cropping, not scaling.  Cropping is also probably commonly needed.

**Comment by jlstevens** [comment]
> ... and so I can ignore the special "op" and "norm" things if I just want to do my own thing

I think that is a fundamentally bad idea because the natural thing to do use are lambdas and lambdas don't pickle. Offering our own objects to cover the majority of cases is much safer.

**Comment by jlstevens** [comment]
In addition, I don't think there is a convenient way a user could specify their own function for normalization. There isn't anything like that in numpy that I know of even then this operation needs to hook up to the HoloViews normalization system e.g to know the min and max values across a ``HoloMap``.

**Comment by jbednar** [comment]
Eventually what we ended up with is better than anything discussed here. :-)
