### ISSUE TITLE
Add norm style option to all colormappable matplotlib plots

### ISSUE THREAD

**Issue by akhmerov** [ioam/holoviews#808]
Right now providing the color normalization similar to http://matplotlib.org/api/colors_api.html#matplotlib.colors.Normalize requires manual modification of the colormap. Since normalization is crucial in particular in diverging colormaps (that's the context where I encountered it), it would be quite useful.

**Comment by philippjfr** [comment]
Most elements should already accept ``norm`` as a style option. If that's not already possible we should add it.

**Comment by akhmerov** [comment]
Is `norm` a function that takes value as input and maps it onto [0, 1] interval? I thought in holoviews `norm` was something else.

**Comment by philippjfr** [comment]
The ``norm`` style option, i.e. the one you set with regular ``%%opts Image (norm=...)``` simply gets passed in as the norm argument to the plotting function so yes, any function that matches the ``matplotlib.colors.Normalize`` API should work.

**Comment by akhmerov** [comment]
That's great to hear. I am seemingly missing it on the `TriSurface` in v1.6.2:

```
WARNING:root:Options: Invalid options ['norm'], valid options are: ['c', 'cmap', 'color', 'ec', 'ecolor', 'edgecolor', 'linewidth', 'lw', 'shade']
```

**Comment by philippjfr** [comment]
Yes, not all Elements support it yet. I'll make a PR ensuring that all subclasses of the ``ColorbarPlot`` class accept a ``norm`` argument.

**Comment by akhmerov** [comment]
Thanks!

**Comment by philippjfr** [comment]
Done that now in the PR above. Closing.

**Comment by jlstevens** [comment]
I would like to mention there was an [FAQ entry](http://holoviews.org/FAQ.html)  that addressed this kind of problem:

**Q**: Why don’t you let me pass matplotlib_option as a style through to matplotlib?

**A**: We have selected a subset of default allowable style options that are most commonly useful in order to hide the more arcane matplotlib options. If you do need such an option to be passed to the plotting system, you are welcome to declare that this is allowed. For instance, say you may want the 'filternorm' option to be passed to matplotlib’s imshow command when displaying an Image element:

```
from holoviews import Store
Store.add_style_opts(Image, ['filternorm'])
```

Not saying I object to adding 'norm' to the style options...just that we had thought about this, even if might have documented it in the wrong place. :-)

**Comment by akhmerov** [comment]
Thanks for the clarification, good to know.
