### ISSUE TITLE
HoloMap images with of different regions (feature request)

### ISSUE THREAD

**Issue by basnijholt** [ioam/holoviews#82]
What I would like to do is to use a HoloMap to zoom in on Images. So for example first I have a few ``Image``'s, then an ``Image`` with a ``hv.Bounds`` and then the same image but with a different `.select()``.

I believe this is not possible at the moment, but it would be really nice.

**Comment by jlstevens** [comment]
I do think this should be possible already or at least it should be! :-)

Let's load up some penguins:

```python
import holoviews as hv
penguins = hv.RGB.load_image('./doc/assets/penguins.png')
```

This holomaps zooms onto the penguins by taking smaller and smaller slices of the RGB image:

```python
hmap = hv.HoloMap()
for i in range(5):
    section = 0.5 - (i * 0.1)
    hmap[i] = penguins[-section:section, -section:section]
```

Anyway, do tell us if that works for you and whether this approach works properly for whatever data you are hoping to zoom in on. I do realize your data is probably more complicated than a simple RGB image in this example but the principle should still apply.

**Comment by jlstevens** [comment]
Yes, it works with overlays and bounds:

```python
hmap = hv.HoloMap()
for i in range(5):
    section = 0.5 - (i * 0.1)
    hmap[i] = penguins[-section:section, -section:section] * hv.Bounds((-0.08, -0.08, 0.08, 0.08))
```

**Comment by basnijholt** [comment]
Thanks for the example, but I would like to do something like:

```python 
import holoviews as hv
penguins = hv.RGB.load_image('/home/bnijholt/holoviews/doc/assets/penguins.png')
hmap = hv.HoloMap()

i = 0 
section = 0.5 - (i * 0.1)
hmap[i] = penguins[-section:section, -section:section] 

for i in range(1, 5):
    section = 0.5 - (i * 0.1)
    hmap[i] = (penguins[-section:section, -section:section] 
               * hv.Bounds((-0.08, -0.08, 0.08, 0.08)))

```

So first show a few images, and then later zoom in.

**Comment by philippjfr** [comment]
As long as the Elements in the HoloMap are consistently of one type you can do whatever you want, which means you simply have to wrap the first few frames in an Overlay:

```python 
import holoviews as hv
penguins = hv.RGB.load_image('/home/bnijholt/holoviews/doc/assets/penguins.png')
hmap = hv.HoloMap()

i = 0 
section = 0.5 - (i * 0.1)
hmap[i] = hv.Overlay([penguins[-section:section, -section:section]])

for i in range(1, 5):
    section = 0.5 - (i * 0.1)
    hmap[i] = (penguins[-section:section, -section:section] 
               * hv.Bounds((-0.08, -0.08, 0.08, 0.08)))

```

That works for me.

**Comment by jlstevens** [comment]
@philippjfr Do you think we could detect such a condition and automatically wrap non-Overlay elements into Overlays as necessary?

This is something like 'type promotion' so it might be useful in many circumstances but could be annoying in others. That said, I think our philosophy should be to make things work whenever possible -  I think it is always better to present the available data in whatever way that works. I think it is probably nicer to automatically wrap elements into Overlays instead of presenting the user with a traceback.

I think this would only ever apply to our two heterogeneous containers. I.e we can stick any single element into an overlay or any single element into a Layout and have something that looks (mostly) the same but with a different type.

**Comment by philippjfr** [comment]
How would you do type promotion here, retroactively convert all none Overlay types if you insert an Overlay? HoloMaps will complain (for good reason) if the Elements types are mismatching, so say you create a HoloMap with a bunch of Images as above and then shove on a few Overlays to the end. When the first Overlay is inserted it would then have to go through all other Elements and upgrade them to Layouts. It's possible but it's a pretty weird side-effect, if you insert one new Element on a HoloMap and suddenly all the other types are changed.

**Comment by jbednar** [comment]
Seems like the arguments for and against such type promotion are both strong.  If not supporting it, then maybe the exception could suggest how to get around the problem, and if supporting it then maybe a warning saying that the type has been promoted would be appropriate.  Either way you'd be pushing people towards explicitly adding the Overlay conversion so that it's clear what's going on.

**Comment by jlstevens** [comment]
It was just a suggestion to consider. What I will say is that if we leave things as they are, we should at least generate a more useful exception message than:

```python
AssertionError: HoloMap must only contain one type of ViewableElement.
```

If it said something along the lines of 'holomap cannot contains types of both X,Y' then that might help people decide what they want to do about it.

**Comment by basnijholt** [comment]
OK, it's clear to me how it works now, but a better error message would indeed help a lot.

**Comment by philippjfr** [comment]
Improved the commit message in ce5d212 closing this issue now.

**Comment by jlstevens** [comment]
Looks good! Hopefully people will be able to find what works more easily now.
