### ISSUE TITLE
Cell 3 of the Containers notebook *looks* wrong

### ISSUE THREAD

**Issue by jlstevens** [ioam/holoviews#85]
The cell under the **Layout subfigure labels** section is so ugly I was convince there was a mistake!

I do realize the point  being made is that you can customize the subfigure labels but the output is so ugly it convinced me there was something wrong with the code (which led to some confusion). I realize the example is actually correct but can we avoid having extremely ugly plots in our official tutorials, even if they are for documentation purposes?

Some suggestions:

* Don't make (1). so small compared to (2). that it is hard to see at first glance giving the impression it is missing entirely (which made me think it is a bug).

* I would make the plot on the left have the  more easily visible subfigure label so it looks less horrible if you don't spot the second label immediately - seeing a (2). without seeing a (1). is more disconcerting than seeing a (1). without a (2).

* I would consider positioning (1). in the middle of the curve plot, not on the right. This illustrates you can position sublabels anywhere you want and this would make it more visible.

* Maybe try to make the font difference obvious but not too extreme?

Now that I know what was being shown I do understand why it looks off. That said, there are some actual bugs with subfigure labelled we need to worry about and first impressions count!

So, this is just something to fix the next time we update these tutorials. My first reaction when seeing a figure shouldn't be to immediately conclude that there is a bad bug to worry about!

**Comment by jbednar** [comment]
Sure, you can do what you like with it. I tried hard to make the default sublabelling look good, which means that changing it doesn't look as good. That should be a warning to people who want to mess with such things that they are likely to make them worse, not better! :-)  

Still, as you realized, there are reasons the example was done that way, precisely to show people how to do different settings in each plot if needed, and making differences large enough to notice them.  

Another issue was to choose formats that some people might actually want to use (not together, of course, as in this case, but both the (1) and (2) option settings are things that people might want to do.  I don't think that putting a sublabel into the middle of the plot would be useful -- who would ever do that?  But putting it inside the plot boundaries *is* important, because it shows that you can do that just as easily as putting it outside (with the advantage of taking less room on the page, but the danger that it may overlap part of the plot).  There isn't room to make (1) bigger (which again is part of the point -- it illustrates the problems with putting such labels inside the plot), but you can make (2) smaller if you like, as long as it's clearly different in size.

**Comment by jlstevens** [comment]
I think just swapping the two plots around so (1) is big and on the left would go a long way towards making it looks less broken. It isn't good when your first reaction to a plot is that something is very wrong!

Obviously not a priority but I might do this the next time we need to update all the reference data for notebook tests.

**Comment by jbednar** [comment]
Yes, swapping the order would probably help clarify it.

**Comment by philippjfr** [comment]
Changed it as discussed above (changed the position of the inset label to the top left of the ItemTable). Closing this issue now.
