### ISSUE TITLE
Boxplot with hue option & mixed up axis labels

### ISSUE THREAD

**Issue by Marigold** [ioam/holoviews#884]
Is there any reason why `hue` option cannot be specified for seaborn boxplots? I'd expect something like this to work

```
# seaborn cmd
# sns.boxplot(x='subject', y='value', hue='group', data=df)

# holoviews
df = pd.DataFrame({'subject': ['A', 'A', 'B', 'B'], 'value': [1, 2, 3, 4], 'group': ['C', 'D', 'C', 'D']})
hv.DFrame(df).clone(x='value', y='subject', hue='group', plot_type='boxplot')
```

However, the `hue` option is only available for `plot_type=pairplot`, `plot_type=facetgrid` and others.

One more thing I've noticed - axis labels get messed up for this example

```
df = pd.DataFrame({'subject': ['A', 'A', 'B', 'B'], 'value': [1, 2, 3, 4], 'group': ['C', 'D', 'C', 'D']})
hv.DFrame(df).clone(x='value', y='subject', plot_type='boxplot')
```

![image](https://cloud.githubusercontent.com/assets/1550888/18825650/c7c00894-83c9-11e6-8f88-2c5a60b54339.png)

Thanks for help! I'd love to push the fix myself, but I've just discovered this awesome library yesterday.

**Comment by philippjfr** [comment]
>Is there any reason why hue option cannot be specified for seaborn boxplots?

No, it's likely just an oversight. However generally the seaborn interface is no longer fully supported and we'd now recommend people use the regular Element types such as ``BoxWhisker`` for this kind of thing. If they don't yet support what you need yet (e.g. coloring by hue) or there's an Element that you need that's missing we can consider implementing that directly, rather than using the DFrame Element.

I'll have a look if there's an easy fix in this case and get back to you.

**Comment by Marigold** [comment]
Awesome, thank you.

**Comment by philippjfr** [comment]
``DFrame`` and the old style box whisker plots have been removed, closing.
